### ISSUE TITLE
"Reboot" watchapp

### ISSUE THREAD

**Issue by Avamander** [InfiniTimeOrg/InfiniTime#101]
It would be very nice to have a watchapp that allows quickly resetting/rebooting the watch. Might allow people to quickly get rid of things like BLE wonkyness without having to wait for battery drain for example.

**Comment by JF002** [comment]
It's already possible to reboot the watch by pressing the button for 5-10s. But I agree, we can add something more user friendly and more visible from the UI!

**Comment by pfeerick** [comment]
Would be a good place to offer a power-down option as well...

**Comment by FlameKat53** [comment]
ooh, can we have it be when you hold the button you have the power down Menu? :o

**Comment by Riksu9000** [comment]
I guess there's not really a need for this anymore.
