### ISSUE TITLE
Disable functions to save energy

### ISSUE THREAD

**Issue by w-s-r** [InfiniTimeOrg/InfiniTime#1010]
### Verification

- [X] I searched for similar feature request and found none was relevant.

### Pitch us your idea!

possibility to disable apps and measurements to save energy

### Description

Being grateful for the development, I usually don't need heart rate measurements, step counter and games. I also don't have a use yet for navigation, music control and notifications.
I'd like to be able to disable those features, have a one-page menu and a less frequent need to recharge the battery.

**Comment by Riksu9000** [comment]
Apps don't use energy unless you use them. You can stop the heart rate measurement from the app if you have started it. We certainly want to minimize the power consumption and efforts towards that are in #53.
