### ISSUE TITLE
Can't reconnect to watch with Gadgetbridge

### ISSUE THREAD

**Issue by arne-fuchs** [InfiniTimeOrg/InfiniTime#1012]
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

Gadgetbridge should be able to reconnect but it doesn't until restart of the watch.

### What should happen instead?

It should be possible to be able to reconnect to the watch after dropped connection.

### Reproduction steps

1. Connect to watch via Gadgetbridge
2. Drop the connection for a while (phone off or out of distance)
3. Try to reconnect to watch via Gadgetbridge

### More details?

I am using a Fairphone with the official LineageOS (Version 18.1). I've downloaded Gadgetbridge via F-Droid.
After loosing connection Gadgetbridge isn't able to connect to the watch until it runs out of battery (no restart option). After that it is able to reconnect.
I've already tried to disconnect completly and reconnect again and also deleting the watch out of the "knwon devices" list but then it is not discoverable anymore until it runs out of battery.
I've found several closed issues like that one but they have been closed so this is why I am opening a new one. It seems that people still have that problem.

### Version

1.8.0

### Companion app

Gadgetbridge 0.65.0

**Comment by Avamander** [comment]
Did you also delete the device from under paired Bluetooth devices in Android settings? 

If this happens from a clean slate on new InfiniTime and Gadgetbridge then unfortunately the most likely issue is that your phone's Bluetooth LE stack is buggy.

**Comment by arne-fuchs** [comment]
The watch is not listed in my bluetooth devices. I've also tried restarting my phone and bluetooth as well as location several times but I still can only reconnect if the watch restarts.

**Comment by Avamander** [comment]
@arne-fuchs 

If you had denied location access and had it turned off then it's not a reportable bug, rather it was a case of not following the very insistent directions provided by the software. 

If however you had granted access and had location enabled and no expected unpaired Bluetooth LE devices could be found, it's a bug in the LineageOS port.
