### ISSUE TITLE
Possibility to increase font size of the notifications

### ISSUE THREAD

**Issue by Jeroen2019** [InfiniTimeOrg/InfiniTime#1029]
### Verification

- [X] I searched for similar feature request and found none was relevant.

### Pitch us your idea!

It would be nice if it is possible to increase the font size of the notifications, its now very small for older people :)

### Description

Under settings an option to change the font size of the notifications panel.

**Comment by Avamander** [comment]
Duplicate of https://github.com/InfiniTimeOrg/InfiniTime/issues/972

**Comment by Jeroen2019** [comment]
> Duplicate of #972

Sorry, didn't look good enough, probably my bad eye's.....
