### ISSUE TITLE
Metronome: tap tempo to establish BPM

### ISSUE THREAD

**Issue by Danimations** [InfiniTimeOrg/InfiniTime#1061]
### Verification

- [X] I searched for similar feature request and found none was relevant.

### Pitch us your idea!

Expanded metronome app: tap a rhythm on the smartwatch to determine its BPM

### Description

The metronome app on Infinitime 1.8.0 is already quite versatile, but as a DJ and musician, there's another metronome function that I'd find extremely useful. I'd like to have the ability to tap on the smartwatch screen, and have the smartwatch determine what the tempo/BPM of my tapping is.

**Comment by Riksu9000** [comment]
This is actually something you can already do by tapping on the middle of the screen.

**Comment by Danimations** [comment]
Brilliant! Many thanks.

**Comment by Danimations** [comment]
After experimenting with this feature, I'd like to suggest a potential improvement. While the tempo-tapping in its current form works, a better result could be achieved if a sample of multiple taps was made, then averaged. For example, the app could measure the intervals between 8 consecutive taps, dive that by 8 and resolve a BPM. The number 8 may not be ideal for non 4/4 time signatures, but it's probably a good starting point as it will supply enough data to improve the accuracy of the end result.

What do you think, @Riksu9000 ?

**Comment by Riksu9000** [comment]
That's certainly a good idea if someone wants to implement that.
