### ISSUE TITLE
Option to disable seconds in Terminal watchface to conserve battery

### ISSUE THREAD

**Issue by ajack2001my** [InfiniTimeOrg/InfiniTime#1071]
### Verification

- [X] I searched for similar feature request and found none was relevant.

### Pitch us your idea!

Remove seconds in Terminal watchface

### Description

As a Pebble user, was thought that high refresh rates to screen eats up battery faster than a low refresh rate to screen. Could the dev of the new Terminal watchface please give users the option to not display the seconds thus extending battery.  

If it is not the case with PineTime and doesn't affect battery life, please delete this feature request.

**Comment by Avamander** [comment]
It probably has a very minor impact, but definitely not something as high as Pebbles. Mostly because the screen is not always on, and if it is, the backlight is most of the consumption.

**Comment by JF002** [comment]
I really don't think this feature would have any measurable impact on the battery life : refreshing the seconds display happens only once a second (which is an eternity in computer time) only when the display is ON and when the terminal watchface is enabled. 
I consider this as an artistic choice from the author, so, unless I'm wrong about the power usage, I guess we can close this feature request.
