### ISSUE TITLE
No Bluetooth in devcontainer

### ISSUE THREAD

**Issue by watertrainer** [InfiniTimeOrg/InfiniTime#1081]
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

There is no Bluetooth available in the devcontainer

### What should happen instead?

There should be Bluetooth available in the devcontainer to install firmware on the watch

### Reproduction steps

Setup the devcontainer like [here](https://github.com/InfiniTimeOrg/InfiniTime/blob/develop/doc/buildWithVScode.md) 
Try to run the [dfu.py](https://github.com/InfiniTimeOrg/InfiniTime/blob/develop/bootloader/README.md#ota-and-dfu)
There will be an error complaining, that `gatttool` is missing.

### More details?

I found some arguments for the `docker run` command, which are supposed to [fix this](https://stackoverflow.com/questions/47264193/hcitool-lescan-ble-or-any-scan-say-hcitool-gatttool-btdevice-l-etc-in), although they seem like a bit of an overkill. Does anyone know if they cause other problems? They didn't for me immediately.

### Version

1.9.0

**Comment by Avamander** [comment]
The container is really for building. Giving it access to the Bluetooth adapter would be fragile and difficult, use tools on the host.
