### ISSUE TITLE
Increase alarm +/- to 5 min

### ISSUE THREAD

**Issue by minacode** [InfiniTimeOrg/InfiniTime#1101]
### Verification

- [X] I searched for similar feature request and found none was relevant.

### Pitch us your idea!

Increase the steps for alarm +/- to 5 min.

### Description

I guess this is controversial, so sorry for that :grin: 

Almost always I am not interesetd in setting a alarm to an odd time (say 10:38), but a lot of the time, I end up tapping the +-button a million times to get to the desired time.

I therefore propose to set the alarm time setting steps to 5 min.
Also, we should then make sure to have an initial time that is divisible by 5, to not end up with something like (3, 8, 13, …).

This would decrease the worst case to 6 taps instead of 30.

**Comment by SteveAmor** [comment]
We could do +5 min and -1 min.  To help speed things up?  Also +5 secs and -5 secs.

**Comment by minacode** [comment]
Maybe, but this increases the worst case to 12 (or 16 with 1-min steps). Also, I fear it may be too unintuitive for a normal user when + and - behave differently. We would at least have to make this very clear in the UI.

**Comment by SteveAmor** [comment]
Plenty of room on the buttons to have the text ```+5``` and ```-1``` 😀

**Comment by minacode** [comment]
Honestly, I am not convinced of asymmetric +/-. I would go either +1/-1 or +5/-5.

**Comment by aiomaster** [comment]
Would it be possible to detect long pressing +/- and to constantly add or decrease the number of minutes?
After 2s holding the step size could increase to 5. So you could fast forward to the time you like and adjust smaller steps by short tapping.

**Comment by watertrainer** [comment]
There was some discussion regarding number-selection in #1093. Other ideas were to have a long press on the buttons for higher increase/decrease or double tap ability (although that would be a bit hard to implement).

**Comment by minacode** [comment]
I like the toggle long press idea. 

Long press could toggle the buttons into a different mode (with something like red background. Super buttons!) that make +/-5 or maybe even +/-10. Another long press would toggle them back to standard gray +/-1.

**Comment by hlessil** [comment]
Just a long-term thought: Upgrading to LVGL 8 would allow replacing the +/- buttons with a roller widget: https://docs.lvgl.io/8/widgets/core/roller.html

LVGL 7 that InfiniTime is currently using has the roller widget too, but it doesn't support styling. The upgrade from 7 to 8 would not be trivial, but I think it'd pay off: #616

**Comment by minacode** [comment]
That would be the best option 😊 But it seems quite far away right now.

**Comment by kieranc** [comment]
Press and hold to quickly increase the time is easy to implement, I've got a UI overhaul for the timer/alarm in the works which does exactly this.

**Comment by minacode** [comment]
I like your work and will close this issue once your changes are merged, because I guess they resolve my initial problem.

**Comment by kieranc** [comment]
Ok, I'll publish the PR as soon as I have the stop button fixed, I should be able to link it to this issue so it'll close when merged.
