### ISSUE TITLE
Option for defaulting to main screen on wake up

### ISSUE THREAD

**Issue by tomburnaer** [InfiniTimeOrg/InfiniTime#1104]
### Verification

- [X] I searched for similar feature request and found none was relevant.

### Pitch us your idea!

An option for the watch to automatically switch back to the main screen on wake up

### Description

Often I'll have a bit of inconvenience with Infinitime where I'll raise my wrist to check the time and find it's stuck in the apps or settings menu, and I've gotta swipe or press the button a few times to get it back to where I need it. Would love to see an option that lets you automatically move it back to the watch face when the screen turns on. Thanks for the great OS👍

**Comment by Riksu9000** [comment]
The trouble is that we can't know if the user intends to keep using the app or not, so either the watch will be in an app when you want to see the watchface, or it will be on the watchface when you want it to be in an app. Having an option is just choosing the lesser of two evils.

This has been discussed in #570, and we concluded that we won't be adding this feature. The user should instead create a habit of long pressing the button to return directly to the watchface when they don't intend to keep using an app.
