### ISSUE TITLE
music app not recognizing music apps

### ISSUE THREAD

**Issue by Crab-9** [InfiniTimeOrg/InfiniTime#1119]
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

the music app doesnt recognize spotify or downloaded music

### Reproduction steps

it just wouldnt recognize 

### More details?

i tried going through the settings on gadgetbridge and tried messing with that but nothing solved it. 

### Version

v1.9.0

### Companion app

Gadgetbridge v0.61.0

**Comment by Riksu9000** [comment]
InfiniTime only interfaces with Gadgetbridge for these functionalities. It's Gadgetbridge that then interfaces with the apps on the phone. Media controls work fine for me, so I think the issue is most likely with the specific apps you're using.
