### ISSUE TITLE
Seedvault notifications spam

### ISSUE THREAD

**Issue by JM480** [InfiniTimeOrg/InfiniTime#1140]
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

When a Seedvault backup notification is visible it spams the PineTime with constant notifications.

### What should happen instead?

The PineTime should only receive the notification once.

### Reproduction steps

Use Seedvault on LineageOS and wait for the app to auto backup.

### Version

1.9.0

### Companion app

Gadgetbridge 0.66.0

**Comment by SteveAmor** [comment]
Thus is a known Gadgetbridge issue.
https://codeberg.org/Freeyourgadget/Gadgetbridge/issues/2611

**Comment by Riksu9000** [comment]
InfiniTime simply displays notifications sent by companion apps. This is not an InfiniTime issue.
