### ISSUE TITLE
Grammar mistake | Infinitime documentation

### ISSUE THREAD

**Issue by aha999** [InfiniTimeOrg/InfiniTime#1144]
Noticed a small grammar mistake, that makes it a little bit confusing.
https://github.com/InfiniTimeOrg/InfiniTime/blob/develop/doc/gettingStarted/gettingStarted-1.0.md

> InfiniTime doesn't handle daylight savings automatically, so make sure to **set the correct the time** or sync it with a companion app.

The issue is in the: _set_ **THE** _correct_ **THE** _time_

**Comment by SteveAmor** [comment]
@aha999 good catch. Would you be able to raise a PR for this?
