### ISSUE TITLE
Haptic alarm app

### ISSUE THREAD

**Issue by Izaic** [InfiniTimeOrg/InfiniTime#115]
It would be awesome to have a haptic alarm app that lets you set an alarm time and then starts vibrating the watch till you tap the screen to confirm that your aware of the alarm.

**Comment by JF002** [comment]
Hi @Izaic ! Good idea, indeed! 
Could you describe your idea with a bit more detail? Maybe a UI drawing? Also, how would you set the alarm time? Using the watch directly, or using a companion app ?

**Comment by vxsbh** [comment]
I think having the ability to set the time on the watch itself would be more practical 🤔

**Comment by Izaic** [comment]
> Hi @Izaic ! Good idea, indeed!
> Could you describe your idea with a bit more detail? Maybe a UI drawing? Also, how would you set the alarm time? Using the watch directly, or using a companion app ?

![image](https://user-images.githubusercontent.com/31933482/99724618-e40ae880-2a81-11eb-9086-960be7becc7f.png)

I stole this from the waspos issue i created on adding a haptic app to waspos as well... As you can see, it's just a plain and simple idea... Tap what time you want it to go off, press a button to confirm the time, and when the time is reached it starts vibrating till to adknowledge it (likely by having a little popup that says "Press ok to stop haptic alarm")

**Comment by Izaic** [comment]
Been using the Wasp-OS haptic alarm app for a few days now and i have to say its an amazing feature! The vibrator in the pinetime is stronger than i though (funnily enough it's stronger than the pinephones)

**Comment by AnirudhAdiraju** [comment]
Hello Izaic!
I have actually finished an alarm app, but there are some issues I need to fix with the logic. I would love for you to check out a demo of it when I get my pinetime up and running again

**Comment by ncartron** [comment]
Agreed, an alarm would be nice - I usually use my watch to wake me up in the morning, and that's definitely one thing which I'm missing right now on my PineTime :)

**Comment by AnirudhAdiraju** [comment]
Would you prefer an alarm set for a certain date and time or just a time and it rings at the nearest instance of that time?

**Comment by Izaic** [comment]
> Would you prefer an alarm set for a certain date and time or just a time and it rings at the nearest instance of that time?

Waspos implements just a time. I guess it doesn't matter though. Would be neat to be able to set different dates with different times.

**Comment by ncartron** [comment]
yes - also, if I were to ask for a "perfect alarm app", recurring alarm (e.g. every day at 7h) would be super nice :)

**Comment by jave** [comment]
I have a pinetime and a fitbit sense. I switch every night to the Sense so it can wake me up, and I switch back to the pinetime in the morning.

The thing I like with the sense alarm: 
- It wakes me every work day, at the same time, but not at weekends (configurable of course)
- Theres a big button on the display I can snooze the alarm, and a smaller button I can dismiss it with, this is useful.

Its convenient to manage the alarm on the watch itself.

It would be nice not to need switching back and forth between the pinetime and the sense, and this is the only feature making me do so. All the other sense features missing in  pinetime are less important, at least IMHO.

**Comment by Riksu9000** [comment]
An alarm app has been included since 1.5.0
