### ISSUE TITLE
Thank You for your work! 

### ISSUE THREAD

**Issue by PrivacyOsint2** [InfiniTimeOrg/InfiniTime#1154]
Many people that I know uses the PineTime watch daily. They love/ would always want more but its great to see how far this project has come! Today I donated to you for your hard work. Gave you a year's donation up front for less fees. Enjoy it you earned it! Thank You again, you are making a real difference in people's lives!!

PS: Love disabling Bluetooth!

**Comment by JF002** [comment]
Thanks for your kind words! It's very rewarding to read such feedback!
