### ISSUE TITLE
Support for Golang/Zig/other for building apps

### ISSUE THREAD

**Issue by devnoname120** [InfiniTimeOrg/InfiniTime#1185]
### Verification

- [X] I searched for similar feature request and found none was relevant.

### Pitch us your idea!

C++ for building apps is hard for many users. I suggest to add support for a compiled language that is fast and with a low runtime footprint.

### Description

MicroPython could be an option but the downside is that it could slow down the otherwise super snappy and battery-saving InfiniTime OS.

**Comment by devnoname120** [comment]
**Zig in particular has**:
- Low memory/CPU footprint
- First-class support for calling C/C++ code.
- Supports C/C++ compilation out of the box so we could switch the whole project to use their compiler and make Zig compilation/integration seemless.

**Comment by Arsen6331** [comment]
Theoretically, this should already be possible, though it would probably be more difficult than just writing the C++ itself. I'd wait for support for uploading apps, which is planned sometime in the future, and then see how those are implemented and do the same in another language.

**Comment by Arsen6331** [comment]
And MicroPython is not really an option. InfiniTime is already running out of RAM as it is, and every new feature uses more RAM. MicroPython would use a lot of RAM and be much slower. If you want MicroPython apps, you can use [WaspOS](https://github.com/daniel-thompson/wasp-os)

**Comment by JF002** [comment]
I agree with @Arsen6331, I think we have many other challenges to overcome before adding more possibilities to build apps. We are already working (experimenting) on offloading resources to the external memory in #321.

**Comment by devnoname120** [comment]
> I agree with @Arsen6331, I think we have many other challenges to overcome before adding more possibilities to build apps. We are already working (experimenting) on offloading resources to the external memory in #321.

Thank you. Are there plans to merge PineTime Lite changes upstream? 🙏
The UI/UX looks more sleek, and even horizontal scrolling is smoother/faster than InfiniTime.

**Comment by Riksu9000** [comment]
Closing as not planned for the time being.

**Comment by devnoname120** [comment]
> Closing as not planned for the time being.

I planned to do it myself, not rely on the maintainers. Given your comments I'll wait a bit however.

**Comment by Riksu9000** [comment]
I could've elaborated on this a bit more. Mainly I think that core InfiniTime apps should just be written in C++ and it's not worth bringing in more dependencies. We aren't in need of more app developers right now either, since there's not that much memory to spare.
