### ISSUE TITLE
Meaning of L_HR in terminal watch face?

### ISSUE THREAD

**Issue by arduino-man** [InfiniTimeOrg/InfiniTime#1217]
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

I don't understand what L_HR stands for

### What should happen instead?

Should say HR only maybe?

### Reproduction steps

I do not understand what the lettler "L" stands for in "L_HR" when using the terminal watch face..

I know HR means heart rate but what is that "L" about?

Thanks

### More details?

No more details

### Version

1.10

**Comment by apilat** [comment]
"HR" only has two letters so it wouldn't line up with the rest of the UI. For what it's worth, I personally use "HBPM".
I would also change "STAT" to something that indicated we mean *Bluetooth* status - for example "BLTH".

**Comment by arduino-man** [comment]
Fair enough but what does the “L” in “L_HR” stand for?

**Comment by arduino-man** [comment]
Seriously, how can this be admitted into the main branch without nobody knowing what that "L" stands for? I know it's weird, but doesn't anyone care? lol.

**Comment by Avamander** [comment]
L as in last measurement. Not a very consequential letter in the end.

**Comment by arduino-man** [comment]
Sorry for reopening this..

I've reached out to the original creator of the watch face ZephyrLabs and can post his response as to the meaning of that "L" shortly as I take the above comment: "L as in last measurement" is only a guess?

Cheers

**Comment by arduino-man** [comment]
LOL turns out the guy who submitted the watch face to InfiniTime simply copied it from someone else's design and has no idea what that "L" stands for.
Picture:
https://user-images.githubusercontent.com/27705324/177205197-b3e8376a-cf99-4faa-9095-9ec3696f2b9a.jpg
