### ISSUE TITLE
Music app keeps counting after BT connection has been lost

### ISSUE THREAD

**Issue by ghost** [InfiniTimeOrg/InfiniTime#1235]
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

music app indicates that the music is still playing after loosing bluetooth connection

### What should happen instead?

the music app should indicate that the connection is lost

### Reproduction steps

1. play music on connected device
2. open music app on pinetime
3. close bluetooth connection
4. music app still increments time played

### More details?

![pinetime_music](https://user-images.githubusercontent.com/54219098/178591392-e538e56e-727f-401d-a042-41e45253307c.jpg)

As you can see on the image, this can even lead to situations, where the time played is greater than a songs length. Also there is no indication that the watch has no connection to the phone. 

Eventually you want to pause/skip the track, and realize only after a few touches  that the music controls are currently not working.

It would be preferable if the music app checks if the bluetooth connection is down and displays an according message, best also in a distinctive color.

### Version

v1.10

### Companion app

Gadgetbridge v0.67.1

**Comment by Avamander** [comment]
I don't think this has a nice solution. We don't know if the music stopped playing or not. 

Connection status itself is visible from the main screen.
