### ISSUE TITLE
Small app list size tweak

### ISSUE THREAD

**Issue by RageGamerBoi** [InfiniTimeOrg/InfiniTime#1241]
### Verification

- [X] I searched for similar feature request and found none was relevant.

### Pitch us your idea!

Widen the app list icons to the edges of the screen

### Description

To make the app list more consistent with the rest of the watch interface (primarily the quick settings menu), widen the app drawer to the edges of the screen.
The PineTime has rather large bezels that make space on the edges in the UI less appealing.

Change the app list from looking like this:

![image](https://user-images.githubusercontent.com/105567407/179781541-9442a0db-e536-4e91-8850-8b52e8461c96.png)

To this:

![image](https://user-images.githubusercontent.com/105567407/180806806-456f3043-0b3d-4508-9547-79cc96aaa6c4.png)

To make it more like this:

![image](https://user-images.githubusercontent.com/105567407/179778313-5629e1bc-7054-40d3-9a23-93e803ba90d9.png)

**Comment by Riksu9000** [comment]
The reason it doesn't go to the edges is because of the scrollbar/page indicator. I think it would need to be redesigned so that it's easier to see and doesn't look bad when above other objects.

**Comment by RageGamerBoi** [comment]
True. I meant to the edges of the available area, somewhat like the current settings menu:

![image](https://user-images.githubusercontent.com/105567407/180320218-277a4538-c746-4a30-bd49-425ad13ff1d8.png)

**Comment by Riksu9000** [comment]
Removing the gap from the left side would make the screen visibly offset. The screen would require more rework to make it larger.
