### ISSUE TITLE
1.10.0 Timer not vibrating

### ISSUE THREAD

**Issue by R715B** [InfiniTimeOrg/InfiniTime#1253]
Once the set timer finishes counting down there is only a single weak vibration.  This occurs both when the screen is on and off.  It does not vibrate as strongly, or continually like the alarm vibrations.  Is this a user error on my part or is it a bug?

**Comment by mashuptwice** [comment]
Your title suggests that there is no vibration at all, while in reality the problem is that the timer vibrates, but only a very short time. Also a duplicate of #391

**Comment by R715B** [comment]
My apologies, I didn't intend the title to be misleading. I didn't know it was already documented, sorry again.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by Riksu9000** [comment]
Closing as a duplicate
