### ISSUE TITLE
Reboot option

### ISSUE THREAD

**Issue by UNIVPM-S1079707** [InfiniTimeOrg/InfiniTime#1319]
### Verification

- [X] I searched for similar feature request and found none was relevant.

### Pitch us your idea!

Add an option in the settings to reboot the device

### Description

Currently, the only way to reboot the device if something wrong happens are to wait that the battery runs out and updating the firmware.

Since it reboots to update the firmware, I don't think it should be hard to have a button in the settings that makes it reboot without updating the firmware.

**Comment by SteveAmor** [comment]
Does holding the physical button to force a reboot fit your requirement?

**Comment by UNIVPM-S1079707** [comment]
It technically does.

**Comment by JF002** [comment]
As @SteveAmor said, you can use the physical button to reboot the firmware. Adding a new entry in the settings is probably not needed.
