### ISSUE TITLE
Temperature app

### ISSUE THREAD

**Issue by minacode** [InfiniTimeOrg/InfiniTime#1327]
### Verification

- [X] I searched for similar feature request and found none was relevant.

### Pitch us your idea!

Make an app that shows the temperature.

### Description

The BMA421/5 can measure temperature. The driver already implements the interface, but the temperature is never used.
We could make an app that shows the temperature. 
I am interested, what values the chip measures. Is it the chips temperature, the body temperature or the outside temperature.
For the latter two, we could maybe approximate the real values from a good parameterized linear function.

**Comment by joseph58tech** [comment]
I never realized the BMA421/5 had a temperature sensor built in. While this is a good discovery, I'm not sure how accurate the temperature displayed will be considering that the sensor is inside of a sealed inclosure.

**Comment by minacode** [comment]
That's why I would like to have some values and wonder if the measurements can be corrected to obtain a "relevant" temperature. My favorite would be the outside temperature.

**Comment by minacode** [comment]
I did #1329 . If you are interested, please take a look at it.

**Comment by minacode** [comment]
I am closing this, because an actual app seems very unlikely, but would like to keep the draft with the experimental implementation open for interested people.
