### ISSUE TITLE
Drag the number in Timer

### ISSUE THREAD

**Issue by TheAwesome98-Real** [InfiniTimeOrg/InfiniTime#1349]
### Verification

- [X] I searched for similar feature request and found none was relevant.

### Pitch us your idea!

You should be able to drag the number in Timer to change it.

### Description

I often have to set a timer for 30 minutes, which means I have to tap the `+` button 30 separate times. It would be great if you could add a feature where you can drag the number to change it quickly.

**Comment by FintasticMan** [comment]
I can't remember if it made it into 1.10, but certainly on the latest develop you can press and hold the button to change the value quickly.

**Comment by TheAwesome98-Real** [comment]
oh
