### ISSUE TITLE
Vibration length/strength adjustment

### ISSUE THREAD

**Issue by thelunarfox75** [InfiniTimeOrg/InfiniTime#1362]
### Verification

- [X] I searched for similar feature request and found none was relevant.

### Pitch us your idea!

Something in the ui to change the vibration length / strength

### Description

last time something like this was posted was a year ago, a response was given telling OP they would be working on something like that and i just wanted some kind of update

I use pinetime with infinitime to help remember to take blood glucose tests, but i've kinda gotten used to the vibrations and wanted to make them a bit longer

**Comment by SteveAmor** [comment]
Duplication of #210

**Comment by minacode** [comment]
There is some adjustment (and place for discussion) in #1328.

**Comment by Riksu9000** [comment]
Closing as a duplicate of #210 or #391
