### ISSUE TITLE
Analog Watch Face Slow Animation

### ISSUE THREAD

**Issue by antonlinux123** [InfiniTimeOrg/InfiniTime#1388]
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

When you swipe back to the home screen from the left side menu a very slow animation plays.

### What should happen instead?

The animation should be much faster.

### Reproduction steps

https://user-images.githubusercontent.com/116518833/197414629-5b53dc47-8fb2-4b81-8dc0-eaa1d7d0f553.mp4

### More details?

I don't know anything else about the bug.

### Version

v1.11.0

**Comment by Avamander** [comment]
Can you please determine that it was faster before?

**Comment by antonlinux123** [comment]
I am not saying that it was faster before I am trying to say that the animation is slower then it should be to feel comfortable this might just be preference though.

**Comment by RageGamerBoi** [comment]
This is because the Analog watch face is very asset heavy and all watch faces need to load every time they’re swiped to.
This results in it loading slower then the ones made with simple rectangles and fonts.
It feels wrong but it’s totally expected.

**Comment by Avamander** [comment]
There are very few ways around that. With effort someone might be able to optimise this but right now it's expected and not really a bug.
