### ISSUE TITLE
Remove unused space-Terminal Watchface

### ISSUE THREAD

**Issue by Uncover-Monetize** [InfiniTimeOrg/InfiniTime#1403]
### Verification

- [X] I searched for similar feature request and found none was relevant.

### Pitch us your idea!

Enlarge font on Terminal by removing unused space

### Description

On the Terminal watch face (my personal favorite) the font is a little small in my opinion, the easiest solution would be to remove some of the blank space at the bottom and up size the font some or perhaps add one blank line between each "entry" for easier separation of items. Maybe also adding an option to hide the HR line item if it's not being used or even the additional user@watch:~ $ that is listed at the bottom. I did look for similar issues but didn't find anything that quite matched this request.

**Comment by Riksu9000** [comment]
The font size can't simply be increased. It's the same font as the rest of the UI and it's rendered at build time.
