### ISSUE TITLE
1.69-inch capacitive screen recommendation

### ISSUE THREAD

**Issue by modi12jin** [InfiniTimeOrg/InfiniTime#1432]
![tb_image_share_1667995100639](https://user-images.githubusercontent.com/40233017/201508013-c263301b-3358-4b43-9f4f-2bdadc13ea98.jpg)

Official Website: www.polcd.com
Alibaba International Station Store: https://polcd.en.alibaba.com/

Recommended reason:
 Screen size 1.69 inches
 Resolution 280*240
 Screen: ST7789V (SPI)
 Capacitive touch CST816T (I2C)
 Touch and screen share one FPC
 Good quality and cheap, if you are in China it's worth 24 rmb（Around $3.4）

**Comment by modi12jin** [comment]
Use this screen video

https://m.youtube.com/watch?v=2TOVohmUqOE&t=5s

**Comment by modi12jin** [comment]
About touch drive, maybe this question can help you guys
https://github.com/fbiego/CST816S/issues/1

**Comment by Avamander** [comment]
Hardware design of the PineTime is not really up to the InfiniTime project to decide upon. Feature and enhancement requests have currently been written down on the Pine64 Wiki article called "PineTime Hardware Wishlist."
