### ISSUE TITLE
music function and VLC

### ISSUE THREAD

**Issue by cr9christi9n** [InfiniTimeOrg/InfiniTime#1452]
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

Functionality NOT OK with VLC in music app

### What should happen instead?

Play and pause plus going to the next or the past one

### Reproduction steps

Hi,
I use 1.11 (it was the same pb in 1.9 verion) version and GadgetBridge on Fairphone 4
I can connect VLC through music app on watch and volume control is OK.

But PLAY AND PAUSE function doesn't work and also going to tne NEXT or PAST song is NOK also !

Thanks in advance and BRAVO for job you do

### Version

1.11

### Companion app

Gadget Bridge 0.71.3

**Comment by Avamander** [comment]
InfiniTime informs the companion app that one of those buttons were pressed, then it's up to the companion app to send that information to other apps. Gadgetbridge uses standard media key events, apps that respect that will function.

It seems that VLC does not respond to those events and there's nothing InfiniTime can do and there's little GadgetBridge could do. This issue should be reported mostly to VLC.

**Comment by cr9christi9n** [comment]
OK I understand your explanation wich is clear ... since it's OK with otbhers apps controle like ANtennaPod or whatever.
Many thanks.
