### ISSUE TITLE
Optional watch faces

### ISSUE THREAD

**Issue by minacode** [InfiniTimeOrg/InfiniTime#1456]
### Verification

- [X] I searched for similar feature request and found none was relevant.

### Pitch us your idea!

The user can decide which watch faces are on the watch. 

### Description

As things seem to go I believe that additionally to the optional apps we also might want some kind of optional watch faces. This way every user can select their favorite watch faces and load them to the watch (or include them in the firmware or whatever). Only those appear in the settings menu for the current watch face. 

This is not needed immediately, but I think the point will come where the list of watch faces gets quite long.

Maybe we could also have 3rd party watch faces, so everyone can build and load their own as they like.

**Comment by JF002** [comment]
This feature has already been asked multiple times. Two options are currently considered : 
 - Build firmware with optional apps : #1114, @1296  & #1408
 - Dynamic applications that user can install at runtime : #1262 

If you don't mind, I'll close this post as duplicate. Feel free to continue the discussion in those topics.
