### ISSUE TITLE
Pressing back button from an InfiniPaint app takes shifted screen

### ISSUE THREAD

**Issue by elektro-NIK** [InfiniTimeOrg/InfiniTime#148]
Pressing back button from an InfiniPaint app during touch takes shifted screen.

Steps to reproduce:
- enter in InfiniPaint app
- touch and hold
- during holding screen press button

Actual behavior:
- screen be shifted 

![IMG_20201205_162657270](https://user-images.githubusercontent.com/8576484/101280662-07000100-37d3-11eb-8611-1a56f3ff4f5e.jpg)
![IMG_20201205_162708325](https://user-images.githubusercontent.com/8576484/101280664-08312e00-37d3-11eb-9073-8ef2694adf0d.jpg)
![IMG_20201205_162716006](https://user-images.githubusercontent.com/8576484/101280665-08c9c480-37d3-11eb-970f-49e1c747df18.jpg)

**Comment by Avamander** [comment]
What InfiniTime version?

**Comment by elektro-NIK** [comment]
0.9.0

**Comment by JF002** [comment]
Looks like there's an issue with vertical scrolling and InfiniPaint! 
This app bypasses LVGL to write on the display, and might not take the vertical scrolling feature into account. I find the offset a bit weird... the vertical scrolling should always scroll 240px on a 320px surface; If an error occurs, the offset should be 80px. On the picture, it looks like it's less (maybe 20px?).

**Comment by elektro-NIK** [comment]
It looks like 10 pixels. If you continue to take these steps, the screen will go full cycle in 32 times

**Comment by LookinR** [comment]
The same thing happened, when I used lvgl.FlushDisplay() in constructor of InfiniPaint. (I'm trying to program Snake-game changing the code of InfiniPaint.) Size is the same as FlushDisplay area height. Maybe some issue with time sequence - FlushDisplay inside of InfiniPaint::OnTouchEvent is done after ending application and redrawing the screen...

**Comment by petterhs** [comment]
While reproducing this, I tried to make the offset go full cycle and return to normal by reproducing multiple times. When the offset was around 50% of screen height the application froze and the new bootloader reverted to earlier version of firmware.

**Comment by tmilburn** [comment]
Appears to be a duplicate issue to #445 but I can't reproduce this in 1.3.0

**Comment by Avamander** [comment]
If this still exists ask for a reopen.
