### ISSUE TITLE
constant device pairing messages from companion app

### ISSUE THREAD

**Issue by dozadoesit** [InfiniTimeOrg/InfiniTime#1489]
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

notifications about device pairing 

### What should happen instead?

I should not be seeing these messages

### Reproduction steps

using gadget bridge on my phone I am constantly presented with these messages:

Device pairing
Your messages are 
available on the device you paired.

I think these may be showing up as a result of notifications that are from applications not on my allow list in notifications settings. Yet when I check my phone I have not been able to correlate a specific application notification with this error. Also if they are not on the list I would think I would get just nothing not a message about Device pairing.  Sometimes I will get these 3 or 4 of them within a few seconds of each other. 

### Version

1.11.0 infinitime

### Companion app

Gadgetbridge.

**Comment by JF002** [comment]
InfiniTime does not emit those notifications by itself, they are most probably generated by an app on your phone and forwarded to your PineTime via gadgetbridge. 

There's not much we can do on InfiniTime side, unfortunately.
