### ISSUE TITLE
Motion sensor doesn't work anymore

### ISSUE THREAD

**Issue by realpixelcode** [InfiniTimeOrg/InfiniTime#1500]
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

The PineTime does not sense any motions anymore.

### What should happen instead?

It should sense motions, count foot steps, wake on raise etc.

### Reproduction steps

I don't know, it just stopped working from one day to another. Perhaps the hardware is broken? But I couldn't imagine why it would be – the watch didn't fall onto the ground or anything.

### More details?

The step counter, Shake Wake, Raise to Wake and XYZ motion diagram don't work at all anymore.

### Version

v1.11.0

**Comment by minacode** [comment]
> Perhaps the hardware is broken?

This is very likely and one of the more frequently reported problems.

**Comment by realpixelcode** [comment]
Hm, is there any way of checking whether it's a software or a hardware problem? (And if it's a hardware problem, can it be repaired?)

**Comment by minacode** [comment]
You could try different softwares. If the problem persists it is most likely a hardware problem. 

I don't know about repairing. I guess its possible in theory.

**Comment by realpixelcode** [comment]
Different software? I don't know of any alternatives to InfiniTime, unfortunately 😕

**Comment by minacode** [comment]
You can try older versions of InfiniTime or WaspOS. But I would bet on a hardware problem.

**Comment by Gernomaly** [comment]
I had the same problem. It was sadly hardware related. I am currently still thinking of a good way to fix it, without having to buy a new one

**Comment by realpixelcode** [comment]
Okay, will close 😕

**Comment by Mindavi** [comment]
You can see if the sensor is detected in the about menu. If there's question marks it's very likely a hardware issue

**Comment by realpixelcode** [comment]
It says:

> Accel. ???

So it's indeed a hardware defect. 😕 I guess it's time for a Bangle.js. Thanks for your help :)

**Comment by sammyj85** [comment]
I'm getting the ??? for Accel also.... sad.

Reflashing the firmware didn't help.
