### ISSUE TITLE
Wakeup no longer working (tapping, shaking, turn wrist)

### ISSUE THREAD

**Issue by ReaderGuy42** [InfiniTimeOrg/InfiniTime#1517]
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

The enabled wakeup options no longer work

### What should happen instead?

I was expecting the watch to "wake" when tapped or shaken

### Reproduction steps

1. ??
2. tap watch
3. not waking up

### More details?

I've reinstalled the firmware (1.11) and it still doesn't wake. I've played around with the one tap, two tap options, but nothing works to wake the watch, besides pressing the physical button.

I also noticed that the shake calibration is completely unresponsive.

I've only had the device for a few days and originally this all worked. I think (!) when I first installed the updated 1.11 it also all worked, but as of yesterday it no longer does.

### Version

1.11

### Companion app

GadgetBridge

**Comment by JF002** [comment]
The sleep mode is probably enabled : swipe right to open the quick actions menu and check the bottom left icon. If it's purple, it means that the sleep mode is enabled, which disables all wake options. 
![image](https://user-images.githubusercontent.com/2261652/211153438-8ed2a98f-5db9-4544-b437-fb96254b859b.png)

Tap on it until it turns green to re-enable them.

**Comment by ReaderGuy42** [comment]
Yup, that was it, that was easy. Thanks!!
