### ISSUE TITLE
Option to only show time on RaiseWrist

### ISSUE THREAD

**Issue by ladidadida** [InfiniTimeOrg/InfiniTime#1687]
Hi there, 
I wonder if it would be possible to add another option, that RaisWrist wakup event would only wake the display for short time, while leaving touch display inactive. Most of times I just want to check the time.

From what I understood, there should be a new state, that could be activated from within UpdateMotion()-function if a certain setting is activated. And probably MotionController::ShouldRaiseWake should be rewritten to be aware of that setting and state. But it looks, that it should be doable in relatively short time.

As long therm C embedded systems developer I thought I'd give it a try and implement it on my own, but I was not aware that C++ nowadays is even worse then bad old Perl. Though, if someone is willing to push me to the right methods, I probably could also help on implementing this.

Thanks & BR Stefan

**Comment by Riksu9000** [comment]
There are issues and [feature requests](https://github.com/InfiniTimeOrg/InfiniTime/discussions/categories/ideas) about this. This issue is tracked in #618.
