### ISSUE TITLE
watch crashes while using game

### ISSUE THREAD

**Issue by C00kie-** [InfiniTimeOrg/InfiniTime#170]
Hello, thanks for the project, awesome work!
I was testing a bit the version 0.10.0
I found bug that lead to watch reboot:
- while using the 2*2 puzzle game, after a few turns (maybe 10), graphics froze and watch reboot itself.
- while use drawing, same behavior.

**Comment by JF002** [comment]
Hi and thanks :)

Does it happen every time you use these apps? After how long?

**Comment by C00kie-** [comment]
Hello. It did happen the two times I used it, for at least a few sec. Just the time to make a few moves on the games.

**Comment by muesli** [comment]
Ran into the same situation yesterday with 0.14.0.

**Comment by MFAshby** [comment]
I can't reproduce this on 1.0.0, drawing and 2048 game seem to work without crashing.

**Comment by kieranc** [comment]
I also cannot reproduce, I believe this is resolved and can be closed.

**Comment by Avamander** [comment]
Closing as it can't be reproduced.
