### ISSUE TITLE
Infineat face, AM/PM indicator not working

### ISSUE THREAD

**Issue by Rathmox** [InfiniTimeOrg/InfiniTime#1701]
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

an M is showing up in the top right corner

### What should happen instead?

AM or PM sould be showing up in the top right cornet

### Reproduction steps

1. Start the watch
2. Set the watch face to "Infineat face"
3. Set the time format to 12-hour
4. on the time screen, an M is displaying in the top right corner

### More details?

picture found on Reddit
![image](https://user-images.githubusercontent.com/55508107/226107946-6e377027-a259-4b57-9346-b8cbcb198ffc.png)

### Version

v1.11.0 FOSDEM Edition

### Companion app

Gadgetbridge

**Comment by SteveAmor** [comment]
Same on standard V1.11.0

**Comment by SteveAmor** [comment]
I'm assuming https://github.com/InfiniTimeOrg/InfiniTime/blob/310ea81eec3bd35e13718dd85e578048ce20eb47/src/displayapp/screens/WatchFaceInfineat.cpp#L443 needs to be ```lv_label_set_text_fmt(labelTimeAmPm, "%s", ampmChar);``` but my dev setup is not in a state to test.

**Comment by SteveAmor** [comment]
> I'm assuming
> 
> https://github.com/InfiniTimeOrg/InfiniTime/blob/310ea81eec3bd35e13718dd85e578048ce20eb47/src/displayapp/screens/WatchFaceInfineat.cpp#L443
> 
> needs to be `lv_label_set_text_fmt(labelTimeAmPm, "%s", ampmChar);` but my dev setup is not in a state to test.

This didn't fix the problem

**Comment by Riksu9000** [comment]
https://github.com/InfiniTimeOrg/InfiniTime/commit/5feccb382a86d304e7cfcdb5a5b04c109bf7771f This will be fixed in the next release.

**Comment by ScanuNicco** [comment]
I recently upgraded to v1.12.0 but I'm still experiencing this issue:

![20230502_145057](https://user-images.githubusercontent.com/30136040/235758758-486ea2ae-0767-40e3-a7a9-250b4c7c1568.jpg)
![20230502_145114](https://user-images.githubusercontent.com/30136040/235758761-438025cc-64de-464c-b477-2918050025c4.jpg)

**Comment by Riksu9000** [comment]
You need to update the resources.

**Comment by ScanuNicco** [comment]
Alright, i'll give that a shot. If this is the case, it might be worth updating the [1.12 release notes](https://github.com/InfiniTimeOrg/InfiniTime/releases/tag/1.12.0) as they say
> The resources package was not updated for this release, so there's no need to re-install it.

**Comment by JF002** [comment]
@ScanuNicco Oh sorry, my bad, I missed [that little change in the resource file](https://github.com/InfiniTimeOrg/InfiniTime/commit/5feccb382a86d304e7cfcdb5a5b04c109bf7771f) when I wrote the release note. I've just updated it. 

Sorry for the confusion!
