### ISSUE TITLE
Notifcations cause music app to close

### ISSUE THREAD

**Issue by dozadoesit** [InfiniTimeOrg/InfiniTime#1703]
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

When a notifcation is recieved the music app closes

### What should happen instead?

the music app should not close

### Reproduction steps

If I have the music app open while listening to music and get a notification ( text message etc. ) I get dumped back to the main watch screen. I then have to reopen the app. While the app is open and I am using it I should not be dumped back to the watch screen. 

### Version

1.11.0 infinitime

### Companion app

0.73.0 gadgetbridge

**Comment by Riksu9000** [comment]
https://github.com/InfiniTimeOrg/InfiniTime/commit/5ef3c0d3be58b6741a9e443e6d2151de2b3a59bc This will be fixed in the next release.
