### ISSUE TITLE
Brightness icon changes to flashlight's brightness when flashlight is closed by swipe

### ISSUE THREAD

**Issue by lorhof1** [InfiniTimeOrg/InfiniTime#1751]
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

When the flashlight is closed by swiping, the quick settings brightness icon is set to the flashlight's brightness

### What should happen instead?

The icon should represent the actual brightness

### Reproduction steps

1. Open the flashlight
2. Set it to a brightness which is not the current main brightness
3. Enable it
4. Swipe from the top edge to close it
5. The brightness icon shows the wrong brightness

### More details?

This only persists until the quick settings are closed and does not occur if the flashlight is closed with the side button. It also does not occur if the flashlight is disabled.

### Version

v1.12.0

**Comment by JF002** [comment]
Fixed by a refactoring of the brightness introduced by the always on feature #1869 !
