### ISSUE TITLE
Pinetime not updating 

### ISSUE THREAD

**Issue by MrMjau** [InfiniTimeOrg/InfiniTime#1778]
I have tried to update to the 1.13 release, but it just doesn't seem to work. I have tried updating it using gadgetbridge and nrfconnect but my pinetime keeps saying failed ![IMG_20230625_110607.jpg](https://github.com/InfiniTimeOrg/InfiniTime/assets/125794634/64bc1324-9563-4172-9ab4-8b3617b77cf3)

![Screenshot_2023-06-25-11-05-32-29_3c2e989be58abe9ca7463ffb1e6967d2.jpg](https://github.com/InfiniTimeOrg/InfiniTime/assets/125794634/1aa1a1ab-d6f6-4f4f-ba5e-6cc3df0643b9)

**Comment by a13xie** [comment]
I have updated using Gadgetbridge without any issues.

**Comment by FintasticMan** [comment]
Ss it says in the README, nRF Connect isn't supported anymore. Try again with Gadgetbridge, and otherwise I'd recommend trying with a different device.

**Comment by ricsim** [comment]
I could update with Gadgetbridge, but Bluetooth does not work.

It does not connect to my Mobile any more.

(Same with 1.12)

So I have to reboot to 1.11 which works again.

 

Any idea how to debug or why it does this with 1.12 und 1.13?

 

CU, Ricsi
 

Gesendet: Sonntag, 25. Juni 2023 um 11:04 Uhr
Von: "Martin" ***@***.***>
An: "InfiniTimeOrg/InfiniTime" ***@***.***>
Cc: "Subscribed" ***@***.***>
Betreff: [InfiniTimeOrg/InfiniTime] Pinetime not updating (Issue #1778)


 

I have tried to update to the 1.13 release, but it just doesn't seem to work. I have tried updating it using gadgetbridge and nrfconnect but my pinetime keeps saying failed

**Comment by MrMjau** [comment]
> As it says in the README, nRF Connect isn't supported anymore. Try again with Gadgetbridge, and otherwise I'd recommend trying with a different device.

I also tried using my iphone and infinilink but it still didn't work

**Comment by a13xie** [comment]
Have you tried restarting the watch?

**Comment by Bugsbane** [comment]
I just updated from 1.11 to 1.12 last week without any issues, but trying to update to 1.13 today fails the same way as the OP. I'm using GadgetBridge 0.74.0 (with all permissions) on a Samsung A51 with Android 13.

**Comment by MrMjau** [comment]
> I just updated from 1.11 to 1.12 last week without any issues, but trying to update to 1.13 today fails the same way as the OP. I'm using GadgetBridge 0.74.0 (with all permissions) on a Samsung A51 with Android 13.

Thats interesting @Bugsbane maybe it's an issue with infinitime 13

**Comment by hawkinspeter** [comment]
I'm also struggling to update from 1.12 to 1.13 using GadgetBridge 0.74.0d-banglejs on Android

It doesn't seem to even start trying to update the watch.

**Comment by Self-Perfection** [comment]
I had connection issues after update 1.12 → 1.13 similar to [issues after 1.11 → 1.12 update](https://github.com/InfiniTimeOrg/InfiniTime/issues/1724#issuecomment-1511615600)

GadgetBridge just could not connect to the device. Well I know the drill now, so I deleted the device connection from Android settings again but could not pair it back from android bluetooth dialog even after several attempts. But adding the device back from GadgetBridge worked. I suggest everyone who have connection issues after 1.12 → 1.13 update try to do the following:
1. GadgetBridge: Hamburger menu → Data management → Export data
2. Remove pairing from Android settings (probably unnecessary)
3. Delete device from GadgetBridge
4. GadgetBridge: Hamburger menu → Connect new device → [perform pairing]
5. GadgetBridge: Hamburger menu → Data management → Import DB

Yet this is not a nice user experience. Prior to 1.12 OTA updates just worked without all this rigamarole.

**Comment by hawkinspeter** [comment]
My issue is not the connecting per se, but trying to upload the 1.13 firmware. After it disconnects, I can just reconnect, but the watch is still on 1.12.

**Comment by Bugsbane** [comment]
I rebooted the watch and then tried again and it actually updated to 1.13 fine. I wonder if it's some issue with needing to have rebooted since 1.12 was first installed and booted?

**Comment by ricsim** [comment]
Thanx.

That worked!

 
 

Gesendet: Sonntag, 25. Juni 2023 um 18:04 Uhr
Von: "Alexander Meshcheryakov" ***@***.***>
An: "InfiniTimeOrg/InfiniTime" ***@***.***>
Cc: "ricsim" ***@***.***>, "Comment" ***@***.***>
Betreff: Re: [InfiniTimeOrg/InfiniTime] Pinetime not updating (Issue #1778)


 

I had connection issues after update 1.12 → 1.13 similar to issues after 1.11 → 1.12 update

GadgetBridge just could not connect to the device. Well I know the drill now, so I deleted the device connection from Android settings again but could not pair it back from android bluetooth dialog even after several attempts. But adding the device back from GadgetBridge worked. I suggest everyone who have connection issues after 1.12 → 1.13 update try to do the following:


	GadgetBridge: Hamburger menu → Data management → Export data
	Remove pairing from Android settings (probably unnecessary)
	Delete device from GadgetBridge
	GadgetBridge: Hamburger menu → Connect new device → [perform pairing]
	GadgetBridge: Hamburger menu → Data management → Import DB


Yet this is not a nice user experience. Prior to 1.12 OTA updates just worked without all this rigamarole.

**Comment by ajira86** [comment]
> I could update with Gadgetbridge, but Bluetooth does not work.

I had the same issue between 1.11 to 1.12 and had to unpair and pair again my device

**Comment by Bugsbane** [comment]
> I had the same issue between 1.11 to 1.12 and had to unpair and pair again my device

Yes, I've had to do that a couple of times, too. Not a lot, but maybe twice ever.

**Comment by MrMjau** [comment]
Do you have to unzip the file by any chance? ( 1.13 )

**Comment by hawkinspeter** [comment]
I've got mine to update by using Siglo on a linux laptop (over bluetooth) instead of GadgetBridge on Android.
