### ISSUE TITLE
536876864 steps on the counter

### ISSUE THREAD

**Issue by Knirps1** [InfiniTimeOrg/InfiniTime#1789]
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

The step counter on the watchface suddenly displayed 536876864 steps.

### What should happen instead?

The step counter should have displayed a few thousand steps.

### Reproduction steps

I don't know how to trigger this bug.

### More details?

I was dancing and afterwards the watch displayed this absurd step count. It could possibly be 2^29 plus around 6000 steps I had already taken that day.
The number on the watch did not change with further steps and stayed the same past midnight. The number got sent to Gadgetbridge and continued to go up there with further steps I took. I haven't restarted the watch since and held off on applying the update to 1.13.0

![Screenshot_20230701-135323](https://github.com/InfiniTimeOrg/InfiniTime/assets/52383078/c13127d8-2c5b-4324-8ef5-974b715366c2)
![IMG_20230630_190751](https://github.com/InfiniTimeOrg/InfiniTime/assets/52383078/b33d8d06-dad3-4367-84e7-944e333aa519)
![IMG_20230630_191120](https://github.com/InfiniTimeOrg/InfiniTime/assets/52383078/68d9f923-4161-4adb-b0be-daf738c02bf7)
![IMG_20230630_191128](https://github.com/InfiniTimeOrg/InfiniTime/assets/52383078/fd41d99c-525e-4c9d-8974-11b3d42071a6)
![IMG_20230630_191134](https://github.com/InfiniTimeOrg/InfiniTime/assets/52383078/b83d624b-e6fe-4acd-880e-62195ec1521f)
![IMG_20230630_191138](https://github.com/InfiniTimeOrg/InfiniTime/assets/52383078/4fc87e0c-c122-46fe-87e2-34cc8de6a28e)

### Version

v1.12.0

### Companion app

Gadgetbridge 0.74.0

**Comment by Boteium** [comment]
probably dead sensor
It's quite common
for example, drop the watch on the floor can cause this

**Comment by Knirps1** [comment]
This appears to be it. The watch did fall  roughly 90 minutes before I saw the absurd count. I'm still unsure, how the step count in GadgetBridge continued to rise, but I it stays at 0 now after I restarted the watch.
