### ISSUE TITLE
Installing of custom firmware reported successfull, but has no effect on the PineTime itself

### ISSUE THREAD

**Issue by lucullusTheOnly** [InfiniTimeOrg/InfiniTime#1793]
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

Upload of custom firmware reports no errors, but changes nothing

### What should happen instead?

The new firmware should be active after upload and be presented to be validated

### Reproduction steps

- Cloned the github repository of Infinitime
- Checked out the 1.11.0 tag
- Added a new Watchface based on the Infineat Watchface
- Compiled successfully using the docker image from docker hub.
- Took the resulting pinetime-mcuboot-app-dfu-1.11.0.zip file and installed it via Gadgetbridge File Installer
- Installing was reported successfull, PineTime rebooted and connected successfully to Gadgetbridge
- My changes were not active. Neither my new watchface could be found in the list, nor the change in the Infineat Watchface itself was visible (a simple change in position of the step value label)
- When navigating to Firmware in the Settings menu I was not presented with the option to validate the new firmware. Instead it showed, that the firmware was already validated (Version: 1.11.0, ShortRef: e823c8ed)

### More details?

I tried:
- Renamed the file before installing
- Created a new branch with my own commit in the repository before building the firmware
- Introduced slight changes into the Infineat Watchface directly (instead of only my new Watchface) (a change in position for the step value label), to check if this change gets installed correctly (which it didn't)
- When I tried updating to 1.12.0 or 1.13.0, I lost the bluetooth connection, which I couldn't restore, even when removing the PineTime from my bluetooth devices and Gadgetbridge and doing a repair in my bluetooth settings (which worked fine). Gadgetbridge was not able to find the PineTime. Resetting to v1.11.0 restores the bluetooth connection and everything works fine as before.
  - I understand, that for the update from 1.11.0 to 1.12.0 and further I need to also update the resource file (which currently cannot be done via Gadgetbridge), though the documentation suggests, that this has to be done after (!) the firmware update, which is not possible for me, since the bluetooth connection is lost.
 
Am I doing something wrong or is this a bug?

### Version

v1.11.0

### Companion app

Gadgetbridge v0.74.0

**Comment by Avamander** [comment]
If the firmware crashes after being started for the first time, then it will automatically fall back to the previously installed version.
