### ISSUE TITLE
Heart rate always shows zero after screen lock

### ISSUE THREAD

**Issue by FirstWithThisName** [InfiniTimeOrg/InfiniTime#1794]
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

When I unlock the screeb the heart rate is always zero.

### What should happen instead?

It should show the last measured value

### Reproduction steps

Unlock the screen, wait until the measuring is done and a value other than zero appiers.

Lock and unlock the screen, and the value is zero again.

### Version

v1.13.0

**Comment by SteveAmor** [comment]
This looks to be a duplicate of #1784

**Comment by FirstWithThisName** [comment]
@SteveAmor that is true. I don't check closed Issues.
But thy is it closed?

**Comment by ajira86** [comment]
As mentioned in first reply of #1784, this subject is related to issue #183
