### ISSUE TITLE
Missing Widget?

### ISSUE THREAD

**Issue by mattklunder** [InfiniTimeOrg/InfiniTime#1815]
### Verification

- [X] I searched for similar issues and found none was relevant.

### Introduce the issue

In my menu of programs, i have one screen with 6 widgets (stopwatch, alarm, timer, steps, heart rate, music) and a second screen with just 5 (pen/drawing, pong, 2048, metronome, navigation).  While I can't remember what it was, I could swear there used to be a sixth widget there.  Am I missing something that I should expect to see?

### Version

1.13.0

**Comment by everypizza1** [comment]
I found out a few days ago that it was an accelerator data page. No clue why it was there.

**Comment by mattklunder** [comment]
Interesting, thanks for that!  Do you see the same mix of widgets that 
I do?

**Comment by everypizza1** [comment]
Yes.

**Comment by mattklunder** [comment]
closing this since what I'm observing appears to be expected, thanks!

**Comment by FintasticMan** [comment]
The motion app was removed in #1603.
