### ISSUE TITLE
Watch face goes blank at times.

### ISSUE THREAD

**Issue by FNTONN** [InfiniTimeOrg/InfiniTime#1864]
### Verification

- [X] I searched for similar bug reports (including closed issues) and found none was relevant.

### What happened?

This specific watch face I like (Casio G7710) goes blank, shows no time or date.

### What should happen instead?

It should show the time and date when I look at it.

### Reproduction steps

After a certain period of time the watch would show a blank screen with the outlines but no time. I will upload a better photo later as I'm a bit busy at the moment. 
![IMG_7197](https://github.com/InfiniTimeOrg/InfiniTime/assets/55706351/da1f25c6-84fb-4300-b0ca-48c3f3e19597)

### Version

v1.13.0

### Companion app

InfiniLink for iOS 16.6 on iPhone 12 Mini

**Comment by FNTONN** [comment]
![image](https://github.com/InfiniTimeOrg/InfiniTime/assets/55706351/0a78e37d-2ccf-4828-8b1d-aaad4ce6abc5)![image](https://github.com/InfiniTimeOrg/InfiniTime/assets/55706351/3e1d8d64-41a9-48ff-bb19-9bbc5f5f0159)

**Comment by mark9064** [comment]
You're probably experiencing #1411. There's a workaround there you can try if you're comfortable with compiling yourself
