### ISSUE TITLE
Timer holds changing time when turning off the watch

### ISSUE THREAD

**Issue by Alerymin** [InfiniTimeOrg/InfiniTime#1992]
### Verification

- [X] I searched for similar bug reports (including closed issues) and found none was relevant.

### What happened?

the timer kept changing when I turned back on my watch

### What should happen instead?

the timer should not change time

### Reproduction steps

1. Activate "Raise Wrist" and "Lower Wrist" in settings
2. Put the watch in sleep mode
3. Turn it on with the "Raise Wrist" function
4. Open the timer
5. Hold a button to make time change fast
6. Use the "Lower Wrist" function to turn off the watch
7. Release the button
8. Turn the calculator back on with any function
9. Timer keeps changing

### More details?

https://github.com/InfiniTimeOrg/InfiniTime/assets/55508107/9a4f4606-f0bb-46fa-bb38-342a790b29c6

### Version

1.14.0

**Comment by mark9064** [comment]
Resolved by #2108. Thanks for the report :)
