### ISSUE TITLE
Can weather support be added?

### ISSUE THREAD

**Issue by hrmckay** [InfiniTimeOrg/InfiniTime#208]
Can retrieving weather data through Bluetooth be added to the Pinetime?  This feature was added to the Pebble watch using Gadgetbridge.  A helper app on the phone called "Weather Notification" can be linked to Gadgetbridge and supplies the weather.  More information can be found here: https://github.com/Freeyourgadget/Gadgetbridge/wiki/Weather

Hugh

**Comment by vbelloir** [comment]
Nice idea!

**Comment by JF002** [comment]
Thanks for you idea! The integration of this functionality will be easier as Gadgetbridge already implements it. We just need someone to work on it :)

**Comment by pfeerick** [comment]
joaquim's pinetimeLite v0.5.0 shows some experimental weather app capability, so progress is being made on this front ;) https://github.com/joaquimorg/PinetimeLite/releases/tag/liteV0.5.0

**Comment by hrmckay** [comment]
Thanks for pointing that out.  However, it looks like they are using a custom version of Gadgetbridge.  The standard version of Gadgetbridge can supply weather by using a helper app.

**Comment by Avamander** [comment]
> The standard version of Gadgetbridge can supply weather by using a helper app.

Also if the Android flavour has a weather provider.

**Comment by bhibb** [comment]
Would love to see this added!

**Comment by gnome71** [comment]
I started working on a weather app on the pinetime to get into writing displayapps. If you want to take a look:
[branch weather](https://gitlab.com/rfc_2324/InfiniTime/-/tree/weather)
It can be updated via bluetooth by a python app which is at:
[branch alert](https://gitlab.com/rfc_2324/wttr-py/-/tree/alert)
I use this script on my PinePhone to update it.
But! Its by far not finished. Work in progress ;-)
