### ISSUE TITLE
Wake-up Alarm does not sound in Sleep mode

### ISSUE THREAD

**Issue by SukiiPooru** [InfiniTimeOrg/InfiniTime#2087]
### Verification

- [X] I searched for similar issues (including closed issues) and found none was relevant.

### Introduce the issue

The  set wake-up alarm does not work in the [blue] sleep mode, it only works in the [green] alerts mode.
If I am sleeping I do not wan't random notifications, hence I put in [ blue ] sleep mode, but I still want the wake-up alarm to sound/vibrate/activate. 
In the [red ] stop mode it is obvious I don't want any notifications or alarms to sound, but in [Blue] wakeup, I want to get up in time (for appointments etc)

### Preferred solution

Blue  sleep mode needs a check for allowing alarm.

### Version

1.14.0

**Comment by mark9064** [comment]
The alarm works fine for me in sleep mode. Could you detail the exact steps you do which causes the alarm not to fire?
Here's what I did to test
- Set alarm for the next minute
- Switch notification mode to sleep
- Turn the screen off by tapping the button
- Observe that the alarm fires and wakes the device

**Comment by SteveAmor** [comment]
I set the alarm for 2 mins in the future. Didn't check with the i. Set to blue sleep. Turned off with button. Alarm fired after 2 mins. V1.13.0 5f3acfad

**Comment by SukiiPooru** [comment]
On Tue, 2024-07-02 at 06:59 -0700, mark9064 wrote:
> The alarm works fine for me in sleep mode. Could you detail the exact
> steps you do which cause the alarm not to fire?
> Here's what I did to test
>  * Set alarm for the next minute
>  * Switch notification mode to sleep
>  * Turn the screen off by tapping the button
>  * Observe that the alarm fires and wakes the device
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
foolishly I didn't think of the 2min ahead test. It worked ok. My
conclusion for the none function alarm was a quirk of crossing time
zone border. Sometimes smart phone doesn't update time for up to many
hours later [ poor signal / not updating changed tower band frequency],
phone must have updated pinetime across the alarm time, hence it didn't
sound. Appologies.

**Comment by mark9064** [comment]
No worries at all, feel free to close this issue if everything is resolved now

**Comment by mark9064** [comment]
Closing this after inactivity. If you encounter this again please feel welcome to open a new issue. Thanks for the report :)
