### ISSUE TITLE
[closed] How to update 1.11.0 to 1.14.0

### ISSUE THREAD

**Issue by cr9christi9n** [InfiniTimeOrg/InfiniTime#2144]
### Verification

- [X] I searched for similar issues (including closed issues) and found none was relevant.

### Introduce the issue

My Infinitime wath is under 1.11 version and I use on my mobile phone (Fairphone 4) the soft GadgetBridge 0.81.0.
I'd like to update to the version 1.14 but I didn't found the file to do it through GadgetBridge.
Anu help?
Many thanks in advance.

### Version

1.11.0 to 1.14.0

**Comment by rambonette** [comment]
Hi @cr9christi9n !
Updating is pretty straight forward. In the [1.14.0](https://github.com/InfiniTimeOrg/InfiniTime/releases/tag/1.14.0) download the `pinetime-mcuboot-app-dfu-1.14.0.zip` on your phone.
Make sure you have Gadgetbrige updated with a version grater or equal to 0.78 and PineTime is connected to you phone and charged.
Open Gadgetbridge > select the Devices tab > click on the three dots on you PineTime tile > File installer > select the .zip file you just downloaded. Update process should complete in few seconds.

Mark this issue as closed if this was helpful.
Friendly reminder: you should use this Issues section to report problems, not to ask for help ;)
For that there's the [Discussions](https://github.com/InfiniTimeOrg/InfiniTime/discussions) tab.

Cheers 🍺

**Comment by cr9christi9n** [comment]
Hi and manythanks @rambonette.
I undestand also for your reminder ;o)
