### ISSUE TITLE
Apple Music Sound Control not working properly

### ISSUE THREAD

**Issue by tituscmd** [InfiniTimeOrg/InfiniTime#2151]
### Verification

- [X] I searched for similar issues (including closed issues) and found none was relevant.

### Introduce the issue

When controlling an Apple Music track and wanting to the increase or decrease volume, it seems to only switch between the loudest option and one below that.

### Version

v1.14.1

**Comment by liamcharger** [comment]
This would need to be fixed in InfiniLink, I would open the issue there :)

**Comment by tituscmd** [comment]
Alright, my bad!
