### ISSUE TITLE
Bluetooth / BLE connection watch face symbol unreliable.

### ISSUE THREAD

**Issue by gillham** [InfiniTimeOrg/InfiniTime#224]
The symbol on the watch face that indicates a Bluetooth connection loses state or fails to update.
Reproduce:
Press the button on PineTime to wake it up.
Connect with nRF Connect 2.4.8 on iOS.
Note symbol appears.
Press disconnect / connect a few times, it should turn on and off.
With nRF Connect in the connected state (and symbol on the watch face), scroll the watch face to the first menu.
Touch the watch app icon to go back to the watch face
Test connectivity / symbol by disconnecting/connecting in nRF Connect, sometimes it is stuck.
If it still works, while connected scroll watch face and go to the "list" icon (information app)
Use the button to return to the first menu
Touch the watch app icon to go back to the watch face
Test connectivity / symbol by disconnecting/connecting in nRF Connect, this is always stuck in my testing.

Going to different apps and back to the watch face will generally reset this and the symbol state will start tracking again.

**Comment by Avamander** [comment]
What InfiniTime version?

**Comment by gillham** [comment]
At least v0.14.1 (currently the latest).
