### ISSUE TITLE
0x8040 linker glitch

### ISSUE THREAD

**Issue by ildar** [InfiniTimeOrg/InfiniTime#254]
I'm using GCC 10.2.0 / binutils 2.35 for building. And I get a strange result for mcuboot binaries:
```
$ objdump -h pinetime-mcuboot-*.out | fgrep .text
  0 .text         0005a474  00008040  00008040  00008040  2**6
  0 .text         0002a7cc  00008040  00008040  00008040  2**6
  0 .text         00032660  00008020  00008020  00008020  2**5
```
So two of three binaries are built for FLASH starting at 0x8040 while the linker script clearly points to 0x8020.

Q: anyone have an idea why this comes out?

**Comment by Avamander** [comment]
I'll close this unless it's still an issue. I've built and ran relatively recent master using latest GCC and it works fine in both mcuboot and no-mcuboot configurations
