### ISSUE TITLE
Random crashes while using music control

### ISSUE THREAD

**Issue by willlovesbearz** [InfiniTimeOrg/InfiniTime#309]
I've had a few crashes while I was using the music control app. they typically happen shortly after opening it. it's the type of crash where the watch locks up and then watchdog resets. this is happening while using the watch with my Pinephone running amazfish on arch linux arm. I have had this happen across al the 1.0.0 release candidates.

**Comment by Avamander** [comment]
It seems that nobody else can reproduce it. If it can be, I'll reopen.
