### ISSUE TITLE
Time format on Quick Actions screen does not honor Time Format setting

### ISSUE THREAD

**Issue by Batcastle** [InfiniTimeOrg/InfiniTime#368]
I'm running Infinitime v1.0.0 and noticed a minor issue:

If you set the time format to 12-hour in the settings app, while the clock face does honor that setting, the clock in the top lefthand corner of the Quick Actions menu stays in 24-hour mode. I feel this clock should honor the same setting as the main clock face.

**Comment by Raupinger** [comment]
Thanks for the bug report. I just fixed it in #370.

**Comment by Riksu9000** [comment]
This hasn't been fixed yet so I believe this should still be open.

**Comment by Batcastle** [comment]
I second that. The PR mentioned above is still open, and there have been no PRs mentioned in either the PR's chat or this one so this issue remains in the master/main branch. It should be reopened.

**Comment by infinitytec** [comment]
Can confirm it is still an issue.

**Comment by trman** [comment]
resolved by  #907 and #927  pr

**Comment by Riksu9000** [comment]
Fixed by #821
