### ISSUE TITLE
Possible mismatch in NavigationService UUIDs

### ISSUE THREAD

**Issue by jonvmey** [InfiniTimeOrg/InfiniTime#434]
Both [NavigationService.md](https://github.com/JF002/InfiniTime/blob/develop/doc/NavigationService.md#service) and a comment in [NavigationService.h](https://github.com/JF002/InfiniTime/blob/develop/src/components/ble/NavigationService.h#L29) refer to the first two bytes of the Navigation Service UUIDs being 0xC7 and 0xE6 respectively, but the actual values generated by the `NAVIGATION_SERVICE_UUID_BASE` macro have `0x00` in the corresponding byte locations.

I'm not sure if this matters or not but it definitely looks suspicious.

**Comment by JF002** [comment]
I think you're right, there is a mismatch between the doc/comment and the code.

The doc you linked to and the comment specify the **old** UUIDs. Later on, we decided to change UUIDs of some custom services to follow a single convention detailed here : https://github.com/JF002/InfiniTime/blob/develop/doc/ble.md#ble-uuids. I think we did this in 0.11.0.

So, the code is right, and the doc and comments should be updated :)
