### ISSUE TITLE
One touch screen

### ISSUE THREAD

**Issue by randb66** [InfiniTimeOrg/InfiniTime#441]
I would like to see together the tilt to wake as well as single touch screen wake up as an option. Not just one or the other but both.

**Comment by Raupinger** [comment]
duplicate of #277

**Comment by JF002** [comment]
and a PR is already on the work : https://github.com/JF002/InfiniTime/pull/290 :)

**Comment by ThePinkUnicorn6** [comment]
I think this can probably be closed now
