### ISSUE TITLE
bug  

### ISSUE THREAD

**Issue by nsupernovae** [InfiniTimeOrg/InfiniTime#496]
version 1.2
Second time this happens, the screen isn't aligned properly. Reboot solves. It seems if I move up/down it gets progressively worse.
The buttons work on as normal.  Thanks!
![11](https://user-images.githubusercontent.com/76794903/126075216-ceb251f1-9cdf-4b53-929c-517d41a20e33.jpg)

**Comment by radmorecameron** [comment]
I think this is a duplicate of #445
