### ISSUE TITLE
Bluetooth 5.2

### ISSUE THREAD

**Issue by moriel5** [InfiniTimeOrg/InfiniTime#501]
Is the Bluetooth stack in InfiniTime still at Bluetooth 5, since 5.1 and 5.2 are already available for the nRF52832 via the proprietary SDK.

It would appear that while not required, upgrading to a newer Bluetooth revision could help in regards to power savings with Bluetooth Audio (issue #500), better support for hearing aids (could be a good feature request in the future) and location/tracking.

**Comment by Avamander** [comment]
NimBLE supports Bluetooth 5.1, switching to the proprietary stack is not going to happen any time soon.

Newer Bluetooth revision wouldn't help with audio, LE Audio is a separate standard that would require specific support.

**Comment by moriel5** [comment]
Yeah, I never meant switching to the proprietary stack, I only brought it as an example that it is possible.

Interesting, Wikipedia explicitly mentions power savings on LE Audio in conjunction with Bluetooth 5.2.

**Comment by Avamander** [comment]
LE Audio itself provides power savings over BT Classic in some cases, but it's not inherit to Bluetooth 5.2 it relies on it.

**Comment by moriel5** [comment]
Ah, thanks for the clarification.

**Comment by JF002** [comment]
I guess the update to an eventual newer version of bluetooth will come with newer versions of NimBLE.
