### ISSUE TITLE
Authentication/Authorization Support BLE Bonding

### ISSUE THREAD

**Issue by GIJack** [InfiniTimeOrg/InfiniTime#502]
EDIT:
Add native authorization using NimBLE

The experts have informed me that the BLE stack they are using supports proper Bluetooth authentication, so this post was edited to reflect that.

**Comment by Avamander** [comment]
NimBLE supports proper bonding, there's absolutely no good reason to reinvent that with anything homebrew, it'd be only pain and misery. With filesystem support the keys created during bonding could be stored properly and kept after a reboot.

**Comment by GIJack** [comment]
> NimBLE supports proper bonding, there's absolutely no good reason to reinvent that with anything homebrew, it'd be only pain and misery. With filesystem support the keys created during bonding could be stored properly and kept after a reboot.

I had no idea that it did, but even better. Lets go with that then.
