### ISSUE TITLE
ubasic

### ISSUE THREAD

**Issue by 0x0000ff** [InfiniTimeOrg/InfiniTime#563]
Would it be feasible or desirable to implement an interpreter such as this one. I think it would be nice because it is lightweight and one could use it to script some simple apps. l

Something like a counter for how many beers you had that turns the text red when you have had a set amount that you'd regard as too many.

**Comment by 0x0000ff** [comment]
Forgot link:
http://dunkels.com/adam/ubasic/

**Comment by Avamander** [comment]
In theory, but you can just copy a few files, rename the classes and write that logic in C++. The thing you explained as an example is really rather simple in C++.

**Comment by JF002** [comment]
I'm closing this feature request right now as this kind of use-case/feature is not in our scope right now.
