### ISSUE TITLE
Firmware freezing after doubletap to sleep

### ISSUE THREAD

**Issue by Riksu9000** [InfiniTimeOrg/InfiniTime#583]
Swipe from QuickSettings to watchface and doubletap during the animation to go to sleep. Now the watch won't wake up and will reset soon.

I could replicate the issue in 1.2.0, but not 1.1.0. Its harder to do in 1.2.0 than 1.3.0.

On 1.2.0 it sometimes just stays at a black screen and it must be reset by holding the button. I didn't get this in 1.3.0.

Can someone confirm this isn't just my watch and some register I may have changed in the touch panel for example that hasn't reset?

https://user-images.githubusercontent.com/37774658/129474007-143e46b6-cf05-4e0f-94e6-6a95fede7fcd.mp4

**Comment by lman0** [comment]
@Riksu9000 what firmware version do you use ? 
because in 1.3.0 i can't reproduce it , since double tap can only awake but not sleep the pinetime

**Comment by Riksu9000** [comment]
This started happening somewhere in between 1.1.0 and 1.2.0 and is still present in latest develop for me.

**Comment by lman0** [comment]
maye it related to the twin things that reset when an refresh is ongoing

**Comment by hubmartin** [comment]
Can confirm I was able to have same reset behaviour with 1.3.0.
(i do not use the analog clock, also never knew I could go back to sleep with doubleclick :) )

**Comment by JF002** [comment]
> (i do not use the analog clock, also never knew I could go back to sleep with doubleclick :) ) 

This is not supposed to happen :-D

**Comment by Avamander** [comment]
If this is still an issue, let's reopen.

**Comment by Riksu9000** [comment]
It is. I think it was after #568 that it doesn't freeze every time, but can cause screen corruption instead.

**Comment by AndreySV** [comment]
still exists in 1.10.0

**Comment by minacode** [comment]
Still exists in 1.11 as well.  
I could not reproduce it in any other setup like the Infineat or the Casio watch face which both also take a little moment to show.

**Comment by mark9064** [comment]
Can anyone still repro this?

**Comment by minacode** [comment]
I cannot reproduce it on 1.15.

**Comment by mark9064** [comment]
Going to close for now, let's re-open this if the problem returns
