### ISSUE TITLE
InfiniTime 1.3.0 Ukrainian characters ignores

### ISSUE THREAD

**Issue by AndriiZ** [InfiniTimeOrg/InfiniTime#588]
InfiniTime 1.3.0 ignores Ukrainian characters (і,ї,є)  when showing notifications (other Cyrillic characters displaying fine)

**Comment by Avamander** [comment]
Have your companion app transliterate while  waiting for larger fonts to be included at some point.

**Comment by Avamander** [comment]
Duplicate of https://github.com/InfiniTimeOrg/InfiniTime/issues/212

**Comment by ITCactus** [comment]
@AndriiZ  i prepared the "fix" for that in PR #887 with support for Ukrainian language.
unfortunately it will not be in mainline/upstream, but you can download my repo, and make a build for yourself.
eventually, i will try to make a release in my fork, but as for now, only DEBUG releases are flashed OK for me, but RELEASE are not (maybe it's relates to some latest changes in the upstream... i will try again after 1.8 release).
