### ISSUE TITLE
Abstraction layer of lvgl widget

### ISSUE THREAD

**Issue by toitoinou** [InfiniTimeOrg/InfiniTime#630]
I do not know a lot above lvgl but when I look at several application code I found that lots of code is duplicated and everything is very verbose.
Perhaps a more object oriented approach by creating a wrapper above lvgl could improve that.

**Comment by Riksu9000** [comment]
In most cases duplicate code could be avoided by simply using loops, but they're not used in most apps for some reason. Similar buttons could be in an array and use an enum. This is what I did in #554. Are there other issues with how it is currently?

**Comment by Avamander** [comment]
> but they're not used in most apps for some reason.

Because iterating over designs is very PITA with such code. The moment you want to change one single element amongst a bunch, you also run into annoyances.

Aside from using up a tiny bit of screen space, there's not a lot why such compaction would matter.

**Comment by Riksu9000** [comment]
> > but they're not used in most apps for some reason.
> 
> Because iterating over designs is very PITA with such code. The moment you want to change one single element amongst a bunch, you also run into annoyances.
> 
> Aside from using up a tiny bit of screen space, there's not a lot why such compaction would matter.

Most was probably the wrong word for me to use. Most objects are different and should be separate but there are some cases where I think using loops could be better. It can make the code easier to read as well.

**Comment by Avamander** [comment]
Let's reopen this if we really feel that this has become a thing we really need.
