### ISSUE TITLE
InfiniTime 1.4.0 Wake on Single Tap Requires Double Tap

### ISSUE THREAD

**Issue by jwillikers** [InfiniTimeOrg/InfiniTime#646]
Since updating to 1.4.0, I now have to tap twice for the PineTime to wake even though the Wake Up setting is set to "Single Tap".

Upon further investigation, Single Tap suddenly started working again by fiddling through different Wake Up settings. Perhaps the issue was caused by a notification? I'll update if I find a way to reproduce the issue.

**Comment by evergreen22** [comment]
Sounds like the settings got corrupted somehow. I had a similar thing happen after installing 1.4.0, double tap didn't work reliably until I went through the wakeup settings.

**Comment by gurg1e** [comment]
I've also noticed that since the 1.4 release raise to wake keeps re-enabling itself after rebooting the watch.

**Comment by Riksu9000** [comment]
Single tap and double tap wakeup seem to work fine. The touchscreen may sometimes have issues detecting touches.
