### ISSUE TITLE
Battery reporting doesn't match (InfiniTime 1.4.0 and GadgetBridge 0.59.2)

### ISSUE THREAD

**Issue by ajack2001my** [InfiniTimeOrg/InfiniTime#649]
GadgetBridge will report a battery of 76% and the PineTime 77%, sometimes it's 2% difference and I've yet to see the two showing the same number. Not exactly a bug, but thought to report it so others are aware if nothing else.

**Comment by Riksu9000** [comment]
This happens because they're not updated in sync. #580 would fix this.

**Comment by Riksu9000** [comment]
This should be fixed
