### ISSUE TITLE
Inconsistent interface in InfiniTime 1.4.0

### ISSUE THREAD

**Issue by ajack2001my** [InfiniTimeOrg/InfiniTime#651]
In most components of the watch, a simple slide down will bring the watch to the previous screen. However, the MUSIC and the TORCHLIGHT app does not behave that way.

**Comment by ajack2001my** [comment]
The games PONG and 2048 as well as the timer (pacing) app does not conform to the slide down as well.

**Comment by Riksu9000** [comment]
Most of these apps use the gesture for something else or the closing gesture is disabled so the app won't be accidentally closed. Flashlight could be fixed and Music could possibly be redesigned to not use vertical swipes.

**Comment by hubmartin** [comment]
I also found no use to swipe in torch to "turn it off".  I would prefer to close it.

**Comment by Itai-Nelken** [comment]
I think the torch should return to the quick settings menu when closed.

**Comment by kennysc** [comment]
> I think the torch should return to the quick settings menu when closed.

I agree, it would seem more logical this way.
