### ISSUE TITLE
PineTimeStyle allows setting colors that hide UI elements

### ISSUE THREAD

**Issue by ajack2001my** [InfiniTimeOrg/InfiniTime#656]
The PineTime Style watchface step counter (the circle on bottom right of screen) is not working. Can somebody else confirm?

**Comment by dyamon** [comment]
How is it not working exactly? To me it wasn't even obvious that was the step counter indicator 😆

At the moment I have ~600 steps and the indicator is pointing at 1 o'clock.

**Comment by ajack2001my** [comment]
What indicator? :)

![PineTimeError](https://user-images.githubusercontent.com/33133105/132827307-72b43299-5148-44fd-b8fc-d267d0501216.jpeg)

**Comment by Riksu9000** [comment]
It's not visible because the indicator is the same color as the background.

**Comment by ajack2001my** [comment]
@Riksu9000 yes, you are right... apologies for the confusion... I feel a little stupid now.... :p

**Comment by Riksu9000** [comment]
Well I think it should still be considered a bug that should be fixed so this issue is fine.

**Comment by kieranc** [comment]
I'm inclined to agree, I'd like to address it in my next update to PTS to make the gauge needle use the existing colors array and also change color in case the background is the same as the needle.
