### ISSUE TITLE
Watch to watch sync

### ISSUE THREAD

**Issue by GIJack** [InfiniTimeOrg/InfiniTime#661]
Here is an idea: watch to watch sync to make sure everyone in a group has the same time. Watch 2 Watch sync.

Put an option in settings to broadcast a timesync command. Add another option that opens a dialog and waits for said broadcast, sets time, and goes back to the watchface.

**Comment by Riksu9000** [comment]
Most devices connected to the internet get the time from a time server, thus everyone should have the same time, and that time is synced to the watch via a companion app. I haven't noticed the time ever drifting.

Have you encountered a situation where this would be useful?

**Comment by Riksu9000** [comment]
You can now also set the time manually on the watch. I don't think there's much demand for this feature.
