### ISSUE TITLE
Battery should be an app

### ISSUE THREAD

**Issue by minacode** [InfiniTimeOrg/InfiniTime#672]
The battery state is found in the settings, but for me, it feels a lot like Steps (at least, both are just a percentage meter). 
It also is no real "setting", because there is nothing to set. 

I do not mean this disrespectful. I just stumbled across this a number of times and it still feels odd to me. 
Maybe this can be a little discussion :)

**Comment by escoand** [comment]
@minacode Nice idea. And this app could show some more information, like "time of disconnect from power" and "time left".

**Comment by minacode** [comment]
Nice idea. I guess #585 would be helpful for that.

**Comment by schneidr** [comment]
I disagree. Battery state is found in the settings in about every OS, that's where most people will look for it. Granted, more details would be nice, but it should stay where it is.
