### ISSUE TITLE
infinitime  1.5.0 lose time if reset when heart rate is enabled 

### ISSUE THREAD

**Issue by lman0** [InfiniTimeOrg/InfiniTime#690]
hi , 

today after installing 1.50 , and validated the firmware.
then i tried to reset in order to check if the time was up after reset 
and it was 

then after i decided to launch the heart rate.
and do a reset again 
and then it lost the time 

so here the description of the  the bug  i found

**Comment by ajack2001my** [comment]
@lman0, unable to reproduce your reported issue. I started the HR app, then pressed the back button to do a reset and the time still displayed correctly. Am I doing something wrong?

**Comment by lman0** [comment]
@ajack2001my in the second reset , infinitme have been  disconnected from phone after time was retrieved 
and phone bluetooth was disabled  also as well.
Otherwise , the smartwatch would have picked instantly the phone , and updated the time on spot

**Comment by JF002** [comment]
I cannot reproduce this issue either. Could you try to shoot a video showing exactly how to reproduce?

**Comment by lman0** [comment]
hi,

i can't no longer test this since my pinetime died . maybe it was a hardware malfunction.
the replacement  pinetime i have (i had buy the 3 pinetime batch) , i can't  reproduce it .
i'm closing it then
