### ISSUE TITLE
Manual step counter reset

### ISSUE THREAD

**Issue by davidhealey** [InfiniTimeOrg/InfiniTime#694]
Is there a way to reset the step counter without having to reboot?

**Comment by OrgansWithoutBodies** [comment]
Maybe have a 'lap' function could be used for whatever you need that for, while being more applicable to most/all users?

**Comment by davidhealey** [comment]
That would work for me. I basically want it as a trip counter so I can see how many steps I've taken on a particular journey.

**Comment by JF002** [comment]
There's currently no possibility to reset the step counter manually. It's automatically reset at midnight, or when the watch resets.

**Comment by stephanie-eng** [comment]
Hey, I saw this issue and implemented this with #764. Let me know if you have any feedback.
