### ISSUE TITLE
Add a way to make customized watch faces

### ISSUE THREAD

**Issue by alphamodh0** [InfiniTimeOrg/InfiniTime#755]
Thanks for your work, I'm exciting with Pine64's proyects. Can U add sny way to add custom watchfaces from the pair app? And a way to share this watchfaces with community.

**Comment by Danimations** [comment]
Glad to hear there's some progress being made on this front. Please keep in mind the prospect of importing a 240x240px .BMP via Bluetooth and using it as a watch background.

**Comment by Avamander** [comment]
Related to https://github.com/InfiniTimeOrg/InfiniTime/issues/321

**Comment by Danimations** [comment]
What do you anticipate will be the best file format and specifications for an image?

**Comment by JF002** [comment]
I've just created a more generic feature request about dynamic app and custom watchface to group multiple requests around that topic. Feel free to continue the discussion in #1262 ;-)
