### ISSUE TITLE
Provide a method to print debug log without disassembling the watch

### ISSUE THREAD

**Issue by happyme531** [InfiniTimeOrg/InfiniTime#760]
Not everyone want to disassemble their watch and buy an debugger in order to fix a simple problem. That is probably a discouraging fact that make debugging much harder and inconveinent.

Could someone implement a protocol to transfer debug log to computer, for example, using the standard Nordic UART protocol?   
There are examples present such as https://github.com/apache/mynewt-core/tree/master/apps/bleuart

**Comment by Riksu9000** [comment]
You don't need a debugger to fix a simple problem. Nowadays there's also InfiniSim.
