### ISSUE TITLE
Scrolling just before DFU starts makes the display glitch out

### ISSUE THREAD

**Issue by Avamander** [InfiniTimeOrg/InfiniTime#77]
When you manage to scroll the exact moment when the DFU is starting, the display glitches out and doesn't seem to recover afterwards.

**Comment by JF002** [comment]
This issue is certainly triggered by a race condition between the SystemTask and DisplayTask that trigger a vertical scroll and the same time...

**Comment by Avamander** [comment]
Might be related to: https://github.com/JF002/Pinetime/issues/91

**Comment by petterhs** [comment]
Is this still reproducible?

**Comment by JF002** [comment]
I'm closing this issue as it's very old. Feel free to re-open if this bug is still present.
