### ISSUE TITLE
Labels overlap in Navigation app

### ISSUE THREAD

**Issue by JF002** [InfiniTimeOrg/InfiniTime#775]
### 

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

Labels (instruction + distance) overlap in Navigation app

### What should happen instead?

Labels should be positionned so they do not overlap

### Reproduction steps

Ashimokawa is working on adding support for the Navigation app in Gadgetbridge (using Osmand) : https://codeberg.org/Freeyourgadget/Gadgetbridge/issues/2387 (branch https://codeberg.org/Freeyourgadget/Gadgetbridge/src/branch/osmand-experiments)

Instruction from Osmand are quite long, so long that the label with the instruction overlaps with the label that displays the distance remaining (pics in French and German):

![osmand](https://user-images.githubusercontent.com/2261652/138475839-55b25654-92c4-4ef9-8b95-1d7a03f77323.jpg)
![gadgetbridge](https://user-images.githubusercontent.com/2261652/138475971-79598ee7-1886-45b4-b1b7-262bc2174d6c.jpg)

### More details?

The UI should probably be reworked so that the labels do not overlap:
 - crop the instruction if it's too long
 - vertically scroll the intruction
 - move the distance label on the side of the icon (either left or right)
 - ...

### Version

1.6.0

### Companion app

Gadgetbridge

**Comment by Avamander** [comment]
I guess this could be fixed when navigation icons are moved to external flash.
