### ISSUE TITLE
Vibrate on hour and half hour

### ISSUE THREAD

**Issue by SteveAmor** [InfiniTimeOrg/InfiniTime#778]
### 

- [X] I searched for similar feature request and found none was relevant.

### Pitch us your idea!

Short double vibrate on the hour and single vibrate on the half hour

### Description

When notifications are enabled, have the option to double vibrate on the hour and single vibrate on the half hour. Like the beeps a Casio watch makes.
I may have a go at this myself but am still getting to grips with the code so if this feature appears popular it's probably best not to wait for me.
Any feedback would be great.

**Comment by SteveAmor** [comment]
Almost finished this. Will raise the PR later today.

**Comment by bakeromso** [comment]
I was actually thinking about implementing something similar! However I had in mind to give a short vibration after 20 or 25 minutes based Pomodoro time keeping techniques. But I'm sure this will do as well.
Anyways, thanks for taking the time to implement this, looking forward to try it out soon!

**Comment by thiswillbeyourgithub** [comment]
Hi, are you interested in implementing vibration for other intervals? Like pomodoro or other (I sometimes work by 7 minute bursts for example).

Also, is it normal behavior to continue vibrating during the night?

Thanks
