### ISSUE TITLE
Pokétch Apps

### ISSUE THREAD

**Issue by moriel5** [InfiniTimeOrg/InfiniTime#779]
During my later childhood, I remember having played Pokémon Diamond version, and well, the in-game gadget there was the "Pokétch" (short for Pokémon Watch) that was what caused me to want a smartwatch (back then, even the term "smartphone" didn't exist, much less "smartwatch").

Now, obviously the Pokétch's interface is very bad for a smartwatch (one button to switch between apps (watchfaces, for those who prefer the term) in a linear fashion, with the only way to get to apps that are earlier in the list is to press the button enough times to get to the end, and then more times to start over, something that gets tiring when there are, I believe it got to at least 16), however the different apps you could get in the game (I would expect them to be detailed over at Bulbapedia) could give some inspirations for any developers wanting to build apps for InfiniTime (such as the calculator or calendar apps).

**Comment by TechnologyClassroom** [comment]
- [X] Digital Watch
- [ ] Calculator
- [ ] Memo Pad
- [X] Pedometer
- [ ] Pokémon List
- [ ] Friendship Checker
- [ ] Dowsing Machine
- [ ] Berry Searcher
- [ ] Day-Care Checker
- [ ] Pokémon History
- [ ] Counter
- [X] Analog Watch
- [ ] Marking Map
- [ ] Link Searcher
- [ ] Coin Toss
- [ ] Move Tester
- [ ] Calendar
- [ ] Dot Artist
- [ ] Roulette
- [ ] Trainer Counter
- [X] Kitchen Timer
- [X] Color Changer
- [ ] Matchup Checker
- [X] Stopwatch
- [X] Alarm Clock

https://bulbapedia.bulbagarden.net/wiki/Poketch

**Comment by dyamon** [comment]
I'm weirdly intrigued by a friendship checker!
*checks watch* Cool, I'm still friends with my buddy Joe!
