### ISSUE TITLE
Display timeout rework

### ISSUE THREAD

**Issue by KawaiDesu** [InfiniTimeOrg/InfiniTime#780]
### 

- [X] I searched for similar feature request and found none was relevant.

### Pitch us your idea!

Allow to configure exact time in seconds for display timeout, separatelly for standby and notifications.

### Description

1. Allow to configure exact time in seconds for screen timeout, not from predefined values. Something like steps target screen, with `-` and `+` buttons.
2. Also, would be much convenient if it possible to configure separate timeout when screen was turned on by notification (and user didn't touch screen or button). This is also can partially solve #367 if vibration turned off when screen timed out too.

**Comment by lordfeck** [comment]
Searching the archives, it seems like someone else already had this thought. A 'reset to watchface' timeout would be a great feature.

I've set the PT to unlock when raising my wrist. Sometimes my sleeve swipes the screen, which makes the InfiniTime enter a menu screen or start an applet. The next time I raise my wrist, the PineTime is still showing the menu screen or applet. 

What would be better to happen is that InfiniTime could timeout and display the home screen after a configurable period of time, i.e. say 5s with no input activity. With the option to toggle this feature on/off.

**Comment by Riksu9000** [comment]
More timeout options have been added, the notification timeout has been set to 7s, and can be cancelled by tapping the screen. I'll consider this issue resolved.
