### ISSUE TITLE
Programmatically generate a notification

### ISSUE THREAD

**Issue by SteveAmor** [InfiniTimeOrg/InfiniTime#781]
### 

- [X] I searched for similar feature request and found none was relevant.

### Pitch us your idea!

InfiniTime apps generate their own notifications using the same UI / UX as notifications received over Bluetooth.

### Description

As far as I can see, there is no way for InfiniTime apps to generate their own notifications using the same UI / UX as notifications received over Bluetooth.
This could be useful for a number of apps, like reaching your step count goal and feature request like #777 and #772 to pick a couple of examples.
Of course, I could be missing something here, so if my request is already possible any pointers would be appreciated.

**Comment by JF002** [comment]
InfiniTime can already generate notification anywhere in the code. For now, notifications are only generated by the Alert Service/Client, but apps are already able to do the same.

See this code : https://github.com/InfiniTimeOrg/InfiniTime/blob/develop/src/components/ble/AlertNotificationClient.cpp#L160

Basically, all you need to do is
 - Instantiate a `NotificationManager::Notification` object and fill its field
 - Push the notification in the notification manager by calling `NoficiationManager::Push()`
 - Notifiy the SystemApp that a new notification have just been generated : `systemTask.PushMessage(Pinetime::System::Messages::OnNewNotification);`

**Comment by geekbozu** [comment]
We should get this added to the developer docs then! Good to know!

**Comment by JF002** [comment]
> We should get this added to the developer docs then! Good to know!

We really need a better developer doc. For anyone interested : https://github.com/InfiniTimeOrg/InfiniTime/projects/6
