### ISSUE TITLE
Standardized Data format

### ISSUE THREAD

**Issue by DerMitDemPunkt** [InfiniTimeOrg/InfiniTime#789]
### 

- [X] I searched for similar feature request and found none was relevant.

### Pitch us your idea!

Structure for local storage of appdata

### Description

As far as i know, the internal memory of the watch is currently not being used by Apps (or at least there is no standard on how to do this).
In my opinion, applications should store non-volatile data such as the number of steps, scores in games or the average heart rate in a standardized structure in a standard format on the local memory. I would use json or xml for this. An alternative would maybe a databased approach like sqlite (probably to much overhead?).

Additional: 
Discussion about whether it makes sense to save all data in one file or whether separate files should be created for each app.
Would you prefer (in the case of json / xml) to create a large file that saves all data from all applications or should each app create its own structure?

Example (json):

{
"infinitime"
&emsp;{
&emsp;"release":"1.7.0"
&emsp;&emsp;{
&emsp;&emsp;"stepcounter":
&emsp;&emsp;&emsp;[
&emsp;&emsp;&emsp;&emsp;{
&emsp;&emsp;&emsp;&emsp;"steps today":"1539",
&emsp;&emsp;&emsp;&emsp;"steps this week":"23764",
&emsp;&emsp;&emsp;&emsp;"steps this month":"44212"
&emsp;&emsp;&emsp;&emsp;}
&emsp;&emsp;&emsp;]
&emsp;&emsp;"paddlegame":
&emsp;&emsp;&emsp;[
&emsp;&emsp;&emsp;&emsp;{
&emsp;&emsp;&emsp;&emsp;"highscore":"12"
&emsp;&emsp;&emsp;&emsp;}
&emsp;&emsp;&emsp;]
&emsp;&emsp;}
&emsp;}
}

Advantages:
* One API to access the data => easy to debug + the app does not have to take care of the storage
* easily expandable (one could write a function that is called after flashing to check if every app has its section  etc)
* flexible (each app has its own area and can save its stuff there regardless of whether it is just one or a few hundred entries)
* little overhead / space-saving (in contrast to "every app saves everything by itself")
* It's neat :)

Cons: (for "one file for all")
* you have to make sure that online one App tries to write to the file at a time

PS:
* I think this is more a "question/diskussion" but i could only choose featurerequest.. 
* This is the first issue i have created so, i hope i've done everything right..
* I have not found anything that covers this topic but if this has already been discussed i'm sorry :)

**Comment by Avamander** [comment]
In general, with Bluetooth LE these kinds of "everything in a single dictionary"-type of data structures from a single source are not good. You're reinventing half of the BLE protocol with it. Including already standardized stuff for exchanging that type of information. For example the key `release` already exists as a characteristic that's well-understood by many.

As a thought exercise, just consider the entire advertisement that data structure you listed and the characteristic/service UUIDs the keys. If you have a new watchapp, take an UUID, make a service, expose the data in characteristics. :boom: done, and you get a bunch more features (`notify`, `read`, `write` etc.) for each key, plus the lack of a feature is easy to detect.
