### ISSUE TITLE
incoming phone call from gadgetbridge continuously vibrates

### ISSUE THREAD

**Issue by clach04** [InfiniTimeOrg/InfiniTime#812]
### 

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

incoming call answered on phone (and hung up) infinitime 1.60 continues to vibrate

### What should happen instead?

should stop vibration when answeerd/hung uo

### Reproduction steps

* call phone
* answer phone, e.g. on handset, car, headphones, etc.
* optional hang up

Watch continues to vibrate

### More details?

Potentially dangerous when driving as dismissing requires looking at watch and taking eyes off road.

### Version

1.60

### Companion app

gadget bridge

**Comment by escoand** [comment]
Duplicate of #367

**Comment by geekbozu** [comment]
Duplicate closing,
Thanks guys :)
