### ISSUE TITLE
Long Press of power button always plays the same animation.

### ISSUE THREAD

**Issue by KoalaV2** [InfiniTimeOrg/InfiniTime#817]
### 

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

Long press of home button always plays coming down animation of watchface even if you are on the notifications menu or settings menu resulting in a weird looking animation.

### What should happen instead?

If on for example the notifications menu i expect it to look like the watchface animation is coming up instead of down. If on the quick access menu i expect the animation to look like it's coming from the right.

### Reproduction steps

1. Be on the latest commit.
2. Go to either notifications menu or quick access menu.
3. Long press power button until it returns to watchface.

### More details?

https://user-images.githubusercontent.com/27083886/140960257-770c10dd-a668-4bb2-a94e-e02ae7a57620.mp4

### Version

Latest git branch.

**Comment by SteveAmor** [comment]
Was this introduced in #782 ?
Does V1.6 work in the way you would expect?

**Comment by KoalaV2** [comment]
> Was this introduced in #782 ? Does V1.6 work in the way you would expect?

I believe that it was introduced there, Since the normal quick press of a button plays the animations just fine but it's the animation that plays when it returns to the watchface after a long press that's the issue.
