### ISSUE TITLE
The letter "I" in top left corner

### ISSUE THREAD

**Issue by rsheink** [InfiniTimeOrg/InfiniTime#819]
Hi all,

From time to time I get the letter "I" it top left corner. Here is a screenshot:

![WhatsApp Image 2021-11-10 at 10 50 04](https://user-images.githubusercontent.com/93521867/141080753-15a3e2de-068b-409e-8595-5d48c624920c.jpeg)

What does this means?

**Comment by Riksu9000** [comment]
This icon shows that you have unread notifications. It will show up if you have your watch set to silent mode in quick settings (bell icon) and you have received a notification.

I don't think this is documented, so maybe this can be considered a documentation issue.

**Comment by rsheink** [comment]
Oh, I understand. Thank you very much.

**Comment by SteveAmor** [comment]
For consistency I raised #776 to move the i to the top left on the analogue watch face.

**Comment by drzacek** [comment]
It would be nice to add "i" to the notification itself. 
We got 5 slots and no way to tell when they came.

**Comment by Riksu9000** [comment]
It is now documented what the icon means.
https://github.com/InfiniTimeOrg/InfiniTime/blob/develop/doc/gettingStarted/gettingStarted-1.0.md#digital-watch-face

**Comment by moriel5** [comment]
I personally think that it would be nice to have several icons, in accordance to the type on notification (if possible), like missed call, text, or miscellaneous.
