### ISSUE TITLE
Notification text in RTL languages scroll in reverse direction

### ISSUE THREAD

**Issue by raananelefant** [InfiniTimeOrg/InfiniTime#851]
See attached video recording

**Comment by raananelefant** [comment]
https://user-images.githubusercontent.com/58908387/144225486-a60ab2d6-6983-4ef9-97be-053ca8677cb6.mp4

**Comment by Riksu9000** [comment]
You are using a fork of InfiniTime, so this issue isn't relevant here. Contact the author of the fork you are using instead.
