### ISSUE TITLE
Littlefs (or similar) datetime backup

### ISSUE THREAD

**Issue by Avamander** [InfiniTimeOrg/InfiniTime#87]
It would be nice if the watch kept track of at least the current date on it's own. 

Writing a new date to a file once a day should be okay in terms of wear, but it'd make the watch much more useful if it needs to reboot in a situation where there's no phone nearby. Plus it'd make date look nicer during testing which constantly resets it.

**Comment by JF002** [comment]
Yes, good idea! We can also write the current date/time to flash just before issuing a reset (after a successful OTA, for example).

**Comment by ZephyrLabs** [comment]
I have a proposal, perhaps we can create a partition in the FS for the SPI flash such that is some sort of EEPROM emulation for non-volatile data, eg. the request for time backup by @Avamander or user settings and other future things... 4Kb of storage should be ample for such a thing..

**Comment by JF002** [comment]
There's no FS in the SPI flash for now. The first 115200KB are used by the boot graphics, the rest is empty. As @Avamander wrote, I think the best would be to use a embedded FS like littleFS to manage the reste of the SPI flash space. 
I think littlefs provides a higher level and easier to use API than a simple EEPROM.
We would be able to use this FS to store configuration parameters, data time, graphic assets, heart rate values,...

**Comment by Avamander** [comment]
> There's no FS in the SPI flash for now. 

@JF002 Working on that right now :)

**Comment by AirHamster** [comment]
What about RAM retention?
We can store time in a certain part of RAM that will be excluded from startup initialization.
And after reboot time can be restored from this part of memory.
https://devzone.nordicsemi.com/f/nordic-q-a/272/ram-banks-ram-retention

**Comment by MysteriousLog6** [comment]
> What about RAM retention?
> We can store time in a certain part of RAM that will be excluded from startup initialization.
> And after reboot time can be restored from this part of memory.
> https://devzone.nordicsemi.com/f/nordic-q-a/272/ram-banks-ram-retention

Ram is volatile memory right?

**Comment by Avamander** [comment]
> Ram is volatile memory right?

Yes. There are sleep modes where RAM contents are kept (with extra power used) and methods to keep some amount of RAM untouched.

**Comment by MysteriousLog6** [comment]
Well what if the device runs out of battery?

**Comment by pfeerick** [comment]
If it runs out, it looses it... simple as that. That's when you would revert to the datetime stored in flash memory. But for reboots, either manual or update related, storing it in RAM would be perfect as it would save a write to the flash memory and preserve the time across the reboot (bar the bootloader/DFU update delay).

**Comment by myxor** [comment]
This could not only be used for date and time but also for other data like steps counter and last hrm result.

**Comment by MysteriousLog6** [comment]
> This could not only be used for date and time but also for other data like steps counter and last hrm result.

I think there is a discussion for this , we could of course do this for a whole lot of other things.

**Comment by kieranc** [comment]
This has been implemented in #595 and can be closed.
