### ISSUE TITLE
Cannot connect to pinetime over bluetooth

### ISSUE THREAD

**Issue by Eshanepicfighter** [InfiniTimeOrg/InfiniTime#870]
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

Got my pinetime in the mail, attempted to update using nRFconnect on iOS, got an eror

### What should happen instead?

Connection would’ve succeeded 

### Reproduction steps

*Unable to describe*

### More details?

![Screenshot 2021-12-08 at 5 58 17 PM](https://user-images.githubusercontent.com/79593316/145304894-99d6d6d9-48ac-4c9a-8d3f-8bd5e591b2d9.png)

### Version

V0.9.0

### Companion app

nRFConnect

**Comment by Avamander** [comment]
Try again until you succeed. 

Follow the guide here for upgrading: https://wiki.pine64.org/wiki/Upgrade_PineTime_to_InfiniTime_1.0.0
