### ISSUE TITLE
Bogus Heart Rate

### ISSUE THREAD

**Issue by muesli** [InfiniTimeOrg/InfiniTime#877]
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

Shows bogus heart rates of >150bpm, even when sitting on a desk

### What should happen instead?

Show accurate heart rates

### Reproduction steps

I noticed that the watch often displays bogus heart rates of >150 bpm. Today I noticed it even shows that rate after receiving a notification while the watch was sitting on my desk.

### Version

v1.7.1

**Comment by ajack2001my** [comment]
Similar to #532

**Comment by muesli** [comment]
Agreed, looks similar. Sorry I didn't find this issue, I promise I looked for one. Closing this ticket hence.
