### ISSUE TITLE
Alarm ringing causes pairing code screen to show

### ISSUE THREAD

**Issue by Itai-Nelken** [InfiniTimeOrg/InfiniTime#882]
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

Every time the alarm rings (even if not connected to companion app), the pairing code screen shows.

### What should happen instead?

The pairing screen shouldn't show.

### Reproduction steps

1. Set an alarm.
  - A companion app (only tested with GadgetBridge) connected and paired or disconnected (but paired) doesn't change anything.
2. Wait for the alarm to ring.

### More details?

I haven't tested on latest develop yet.

### Version

develop 85a25302bfac215f9ec7b993f6a2c21a20ee223b with pr's #698, #720, #648, #821, #557

### Companion app

GadgetBridge 0.62.0 (from FDroid)

**Comment by evergreen22** [comment]
Already fixed in develop with #874

**Comment by Itai-Nelken** [comment]
Sorry, I missed that pr!
