### ISSUE TITLE
{Question] Milestone 1.8.0 is complete?

### ISSUE THREAD

**Issue by ajack2001my** [InfiniTimeOrg/InfiniTime#917]
Is there is reason why 1.8.0 hasn't been released yet? Asking as all milestones have been met.

I am eager to update my PineTime as current build has some annoying bugs (see my bug reports) and I hope the 1.8.0 fixes it.

**Comment by Riksu9000** [comment]
It will be released when we feel it's ready. Milestones aren't necessarily representative of progress towards a release as things can always change. Please be patient :)

**Comment by JF002** [comment]
I had originally planned to release 1.8 yesterday but had to deal with private matters instead sooo... I've just released it a few minutes ago  : https://github.com/InfiniTimeOrg/InfiniTime/releases/tag/1.8.0. Enjoy!
