### ISSUE TITLE
Tracking steps between Gadgetbridge and PineTime seems inaccurate...

### ISSUE THREAD

**Issue by ajack2001my** [InfiniTimeOrg/InfiniTime#928]
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

I walked and GB reported I took 536millions steps by mid day

### What should happen instead?

Typically around 5k steps by mid day

### Reproduction steps

Don't know...

### More details?

![WhatsApp Image 2022-01-11 at 5 49 08 PM](https://user-images.githubusercontent.com/33133105/148920827-6057017c-beca-4ccd-a166-405e932055e2.jpeg)
![WhatsApp Image 2022-01-11 at 5 54 47 PM](https://user-images.githubusercontent.com/33133105/148920894-311fab8a-7e36-466c-8ed6-b4dbd87914cb.jpeg)

### Version

1.8.0

### Companion app

GB 0.64.0

**Comment by ITCactus** [comment]
i have never experienced such an issue, even during implementing steps sync support for Gadgetbridge.
could it be some issues with Gadgetbridge in "Settings -> About you"?
also, did you try to remove device from Gadgetbridge, and do a clean pair like a new device...

anyway, it's unlikely the InfiniTime issue, but anyway can you look in Gadgetbridge logs e.g. in Android Studio?
step sync should look like this:
`D/nodomain.freeyourgadget.gadgetbridge.service.btle.BtLEQueue: characteristic changed: 00030001-78fc-48fe-8e23-433b3a1942d0 value: 0x08 0x00 0x00 0x00
D/nodomain.freeyourgadget.gadgetbridge.service.devices.pinetime.PineTimeJFSupport: onCharacteristicChanged: MotionService:Steps=8
D/nodomain.freeyourgadget.gadgetbridge.service.devices.pinetime.PineTimeJFSupport: adding 8 steps
`
do you see correct values, or those are already in thousands?

@JF002, @Avamander, just wondering if it could be a side effect of  the feature mentioned as ["secure pairing"](https://github.com/InfiniTimeOrg/InfiniTime/releases#:~:text=For%20now%2C%20the,secure%20pairing%20mode!) ?

**Comment by Avamander** [comment]
@ITCactus unlikely to be the cause.

Must've been a communication error somewhere, given the fact that it's nonreproducible I don't think we can do anything here.

**Comment by ITCactus** [comment]
well, for the first time i noticed some issue with steps counter - today PineTime/InfiniTime counted only about 400 steps instead of couple of thousands. and no steps info on charts in Gadgetbridge at all...
unfortunately, that version of Gadgetbridge is not debugable, and all i can see is logs (after enabling those in GB settings). and in logs i see that sync steps from InfiniTime  to Gadgetbridge is ok, but those are not added for some reason.

**Comment by aereaux** [comment]
I've been experiencing some issues like this, where the value in gadgetbridge will be significantly more than the value on the pinetime.  It happens somewhat often, although I haven't found a way to definitively reproduce it.  Is there anything I can do to help debug this?
