### ISSUE TITLE
No response from hardware button

### ISSUE THREAD

**Issue by Mentate** [InfiniTimeOrg/InfiniTime#929]
After updating to 1.8.0 the hardware button fails to respond at all. It no longer has any effect on the watch, including the long press to shut down feature.

Behavior:
No response when hardware button is pressed. 

Expected Behavior:
For the watch to respond when the button is pressed

After a rollback to the previous firmware, the hardware button began working again.

**Comment by Avamander** [comment]
If you repeat the update, does it reoccur?

**Comment by Mentate** [comment]
I installed it on my dev watch first, and when the button failed I assumed I had messed up the hardware so I installed it on my main watch and had the same results.

**Comment by Mentate** [comment]
I should mention that I compiled it myself.

**Comment by JF002** [comment]
@Mentate  Could you try with the build [from the release note](https://github.com/InfiniTimeOrg/InfiniTime/releases/tag/1.8.0) to eliminate the possibility your build is faulty?

**Comment by honyczek** [comment]
Hi, I've updated my watch today from official 1.7.1 to official 1.8.0 and after successful download of firmware watch went to reboot, but never started up. Hardware button doesn't work as hard reset nor power on. After trying to charge watch it is still off. I have Gatgetbridge 0.65.0 and sealed PineTime...

**Comment by Riksu9000** [comment]
@Mentate Did you try the official release build? Do you still have this issue?

**Comment by Mentate** [comment]
Sorry for the bad delay in response, using the official repo corrected the issue, must have been something wrong with my build change
