### ISSUE TITLE
🤝 Thank you InfiniTime Team

### ISSUE THREAD

**Issue by cinimodev** [InfiniTimeOrg/InfiniTime#930]
As a hard-of-hearing person using a PineTime, I want to say thank you.

I am extremely hard-of-hearing and have been since I was a teen. I know most people use wearables for fitness. For me, smartwatches enable me to know about messaging, phone calls, alarms, and other phone notifications I would not be able to hear no matter how loud or how close the device is. For the most part, this is a quality of life improvement because nearly all notifications aren't really that important. 

But, last week it was critical I did not miss any notifications after someone in my family was assaulted. Having my wrist immediately notify me of messages and phone calls were and continues to be imperative. We also have security cameras around our home and I need to be notified immediately of any movement so I can see if I need to call the police. I cannot rely on audible notifications for these alerts. 

I am so grateful for this project and how feature-rich and reliable it is. The fact that I can have these notifications on a device without having to sacrifice my privacy has been simply amazing. 

Thank you to this team for what you do.

**Comment by JF002** [comment]
Thank you **very much** for those feedback :heart: !

Knowing that InfiniTime provide such use-cases I could not have imagined is really heartwarming and motivating!
I'm really happy the PineTime and InfiniTime bring you so much comfort and security!

And I hope everything is fine for your family member now! :crossed_fingers:
