### ISSUE TITLE
Status bar shows wrong time format

### ISSUE THREAD

**Issue by Mentate** [InfiniTimeOrg/InfiniTime#931]
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

The time in the status bar above the app list page is in 24 hour format

### What should happen instead?

It should be in the same format as the settings specify

### Reproduction steps

Go to settings and set the time to 12 hour format. Go to the apps list and in the top status bar the time is still in 24 hour format. 

### Version

1.7.1

### Companion app

GadgetBridge

**Comment by moriel5** [comment]
While I don't believe that this is a bug, but simply an unimplemented (but planned), yeah, I would prefer it to show in a 12 hour format.

Currently, I believe that the toggle only changes the format on the watchface/main screen.

**Comment by moriel5** [comment]
@Itai-Nelken Thanks, I guess in that case that is either a bug or an oversight?
