### ISSUE TITLE
Switch positions for "+"/"-" buttons to avoid display beeing hidden most of the time

### ISSUE THREAD

**Issue by marbetschar** [InfiniTimeOrg/InfiniTime#933]
### Verification

- [X] I searched for similar feature request and found none was relevant.

### Pitch us your idea!

"+" Button is more often pressed than "-". Therefore, switching positions ensures the display is more often visible while pressing one of the two buttons.

### Description

The below screenshot shows the issue very well: Whenever I use the Timer or Alarm app, i basically start with a clock set to 0:00 and need to tap on "+". Unfortunately, while tapping the finger hides nearly the whole screen.

IMHO it would make sense to switch positions for "+" and "-" buttons, so we end up with "+" at the bottom. This has the positive effect of avoid hiding most of the display most of the time:

![Screenshot from 2022-01-14 07-57-49@2x](https://user-images.githubusercontent.com/392542/149465441-95ecdf8f-5a45-47e3-8ea2-13290123e9ea.png)

**Comment by Riksu9000** [comment]
Is this still an issue with the new timer in 1.10.0? Plus being above seems more natural to me.
