### ISSUE TITLE
Shake return to main screen

### ISSUE THREAD

**Issue by rostislavYurievich** [InfiniTimeOrg/InfiniTime#943]
### Verification

- [X] I searched for similar feature request and found none was relevant.

### Pitch us your idea!

Use shake gesture to return to main screen

### Description

It resolves issue, when you want to see the time, but there is a some menu open. To close this menu you need to use your second hand.

**Comment by ItzSwirlz** [comment]
Shaking would be an issue because if I'm playing 2048 or Pong or whatever, and I move my arm it can be problematic.

What I am trying to look into, since my PineTime button broke/fell off, as I wait to 3D print it, is to have a 7 second touch screen to return to home.

**Comment by Riksu9000** [comment]
#1592 tracks the issue where you can't see the time in apps.
