### ISSUE TITLE
When on a call, rejecting an incoming call ends the current call

### ISSUE THREAD

**Issue by pbryan** [InfiniTimeOrg/InfiniTime#952]
### Verification

- [X] I searched for similar bug reports and found none was relevant.

### What happened?

While on a call, received an incoming call, and notification; rejecting the call on InfiniTime ended the current call.

### What should happen instead?

Rejecting the incoming call in InfiniTime should reject the incoming call.

### Reproduction steps

1. Install GadgetBridge on Android phone.
2. Receive a call on Android phone.
3. While on call, receive another incoming call.
4. Reject the second incoming call in InfiniTime.
5. Observe that the current call has been terminated.

### More details?

Hardware: PineTime.

### Version

1.8.0

### Companion app

GadgetBridge 0.64.0

**Comment by JF002** [comment]
I think this is an issue for Gadgetbridge. InfiniTime does not know if the call notification corresponds to a "first call", or to a second call coming on top of the 1st one, it just receives a call notification from Gadgetbridge and notifies Gadgetbridge when the "reject" button is tapped.

**Comment by pbryan** [comment]
OK, thanks, I'll raise it in GadgetBridge.

**Comment by JF002** [comment]
It would be nice to know if this feature is supported by other devices and how it's implemented. Maybe we'll need to extend the current API to support multiple calls.

**Comment by pbryan** [comment]
Here is the [Gadgetbridge issue](https://codeberg.org/Freeyourgadget/Gadgetbridge/issues/2568).

**Comment by pbryan** [comment]
Will update this issue as I learn more.
