### ISSUE TITLE
Support for counting lanes while swimming

### ISSUE THREAD

**Issue by CountOmega** [InfiniTimeOrg/InfiniTime#962]
### Verification

- [X] I searched for similar feature request and found none was relevant.

### Pitch us your idea!

Support for counting lanes while swimming

### Description

It would be nice if the PineTime supported counting lanes while swimming
 The Mi band 5 can do this. It counts the lanes swam and the metres in total.

**Comment by Avamander** [comment]
The PT really isn't waterproof enough to make this a safe feature to offer.

**Comment by NordMike** [comment]
> The PT really isn't waterproof enough to make this a safe feature to offer.

What if a better sealed case were made?
