### ISSUE TITLE
Option to remove notifications

### ISSUE THREAD

**Issue by DoveCannon** [InfiniTimeOrg/InfiniTime#983]
### Verification

- [X] I searched for similar feature request and found none was relevant.

### Pitch us your idea!

I want to be able to clear my notifications like other watches

### Description

Right now my watch shows the 5 latest notifications, regardless if I've seen them or not. I'd like an option to be able to remove notifications that have been seen.

**Comment by SteveAmor** [comment]
Duplicate of #176 ?

**Comment by Avamander** [comment]
Yes, duplicate of #176

**Comment by Sokoloft** [comment]
I just got mine today. Odd this isn't a feature. I assume it'll go away at midnight? I'd hope so or else the notification feature is useless.
